---

- name: Gather Facts and set Variables
  tags: always
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  pre_tasks:
    - name: Pre Tasks - Gather Facts and set Variables
      ansible.builtin.import_tasks: tasks/basic_all/config_workstation-ansibleFacts.yml

# become: true # auskommentiert, wg Fehler bei alias-aufruf "upnvm":
# [ERROR]: Task failed: Duplicate become password prompt encountered waiting for become success.
# bei jedem der subtasks ist become:true gesetzt
- name: Add repos + update + config package manager
  hosts: localhost
  connection: local
  # become: true
  pre_tasks:
    - name: Pre Tasks - config pacman
      ansible.builtin.import_tasks: tasks/basic_all/config_workstation-pacman.yml
    - name: Pre Tasks - addrepos
      ansible.builtin.import_tasks: tasks/basic_all/config_workstation-addrepos.yml
    - name: Pre Tasks - all update
      ansible.builtin.import_tasks: tasks/basic_all/all_update.yml

# Create / Include btrfs snapshots in GRUB boot options
# - name: Install and config snapper+btrfs
#   hosts: localhost
#   connection: local
#   become: true
#   tasks:
#     # wird in init-install-Script erledigt, da vor Inst aller (init) Software schon eingerichtet sein soll
#     # + müsste hier entsprechend angepasst/aktualisert werden
#     #
#     # - name: Install packages - snapper+btrfs
#     #   ansible.builtin.import_tasks: tasks/basic_all/packages_workstation-snapperBtrfs.yml
#     - name: Config Services - snapper+btrfs
#       ansible.builtin.import_tasks: tasks/basic_all/config_all-services-snapperBtrfs.yml

- name: Software, Firewall, Servcices, VM, User, Settings, etc
  hosts: localhost
  connection: local
  become: true
  tasks:
    # ----------------------------------------------------------
    # ### Entfernen nicht benötigter vorinstallierter Pakete
    - name: Entfernen nicht benötigter vorinstallierter Pakete (Gnome)
      ansible.builtin.import_tasks: tasks/Desktop_Gnome/packages_workstation-Gnome-removePreInstalls.yml
    # TODO: Update + Test:
    # - name: Entfernen nicht benötigter vorinstallierter Pakete (Plasma)
    #   ansible.builtin.import_tasks: tasks/Desktop_Plasma/packages_workstation-Plasma-removePreInstalls.yml
    #
    # ----------------------------------------------------------
    # ### Install software packages, including Flatpak, Snap:
    - name: Basic packages
      ansible.builtin.import_tasks: tasks/basic_all/packages_workstation-basic.yml
    # - name: Packages Plasma
    #   ansible.builtin.import_tasks: tasks/Desktop_Plasma/packages_workstation-Plasma.yml
    - name: Packages Gnome
      ansible.builtin.import_tasks: tasks/Desktop_Gnome/packages_workstation-Gnome.yml
    - name: Packages Gnomeshell
      ansible.builtin.import_tasks: tasks/Desktop_Gnome/packages_workstation-gnomeshellstuff.yml
    #
    # ex 'local packages install':
    - name: Citrix Workspace App (ICA-Client) packages
      ansible.builtin.import_tasks: tasks/basic_all/packages_workstation-citrixWorkspaceApp-icaclient.yml
    - name: Config - fix for CitrixIcaclient on Gnome
      ansible.builtin.import_tasks: tasks/fix/config_workstation-Gnome-citrixIcaclient.yml
    - name: Visual Studio Code packages
      ansible.builtin.import_tasks: tasks/basic_all/packages_workstation-vscode.yml
    - name: Zed Editor packages
      ansible.builtin.import_tasks: tasks/basic_all/packages_workstation-zed.yml
    - name: Fonts
      ansible.builtin.import_tasks: tasks/basic_all/packages_workstation-fonts.yml
    - name: Starship Shell Prompt
      ansible.builtin.import_tasks: tasks/basic_all/packages_workstation-starship.yml
    - name: Zsh plugins
      ansible.builtin.import_tasks: tasks/basic_all/packages_workstation-zsh-plugins.yml
    #
    # - flatpak:
    - name: Config Flatpak
      ansible.builtin.import_tasks: tasks/flatpakSnap/config_workstation-flatpak.yml
    - name: Packages Flatpak
      ansible.builtin.import_tasks: tasks/flatpakSnap/packages_workstation-flatpak.yml
    #
    # - snap:
    # - name: Config Snap
    #   ansible.builtin.import_tasks: tasks/flatpakSnap/config_workstation-snap.yml
    # - name: Packages Snap
    #   ansible.builtin.import_tasks: tasks/flatpakSnap/packages_workstation-snap.yml
    #
    # ----------------------------------------------------------
    # ### Config Firewall, Cron, Services, sonstige Settings:
    - name: Config - stats all
      ansible.builtin.import_tasks: tasks/basic_all/config_all-stats.yml
    - name: Config - Firewall all
      ansible.builtin.import_tasks: tasks/basic_all/config_all-firewall.yml
    - name: Config - Firewall workstation
      ansible.builtin.import_tasks: tasks/basic_all/config_workstation-firewall.yml
    - name: Config Settings all - GRUB
      ansible.builtin.import_tasks: tasks/basic_all/config_all-settings-grub.yml
    - name: Config Settings all - locale
      ansible.builtin.import_tasks: tasks/basic_all/config_all-settings-locale.yml
    - name: Config Settings all - direnv
      ansible.builtin.import_tasks: tasks/basic_all/config_all-settings-direnv.yml
    - name: Config Settings all - rclone
      ansible.builtin.import_tasks: tasks/basic_all/config_all-settings-rclone.yml
    - name: Config Settings all - starship
      ansible.builtin.import_tasks: tasks/basic_all/config_all-settings-starship.yml
    - name: Config Settings all - ghostty
      ansible.builtin.import_tasks: tasks/basic_all/config_all-settings-ghostty.yml
    - name: Config Settings all - ansible update-by-tag
      ansible.builtin.import_tasks: tasks/basic_all/config_all-settings-ansible-updateByTag.yml
    - name: Config Settings all - bashrc
      ansible.builtin.import_tasks: tasks/basic_all/config_all-settings-bashrc.yml
    - name: Config Settings all - zshrc
      ansible.builtin.import_tasks: tasks/basic_all/config_all-settings-zshrc.yml
    - name: Config Settings all - zshrc - plugins
      ansible.builtin.import_tasks: tasks/basic_all/config_all-settings-zsh-plugins.yml
    - name: Config Settings all - PowerShell profile
      ansible.builtin.import_tasks: tasks/basic_all/config_all-settings-PowerShellProfile.yml
    - name: Config Settings all - nnn plugins
      ansible.builtin.import_tasks: tasks/basic_all/config_all-settings-nnnPlugins.yml
    - name: Config Settings all - xterm - Xresources
      ansible.builtin.import_tasks: tasks/basic_all/config_all-settings-xterm.yml
    - name: Config Settings all - vimrc
      ansible.builtin.import_tasks: tasks/basic_all/config_all-settings-vimrc.yml
    - name: Config Settings all - Vim plugins
      ansible.builtin.import_tasks: tasks/basic_all/config_all-settings-vim-plugins.yml
    - name: Config Settings all - ClamAV
      ansible.builtin.import_tasks: tasks/basic_all/config_all-settings-ClamAV.yml
    - name: Config Settings all - reflector
      ansible.builtin.import_tasks: tasks/basic_all/config_all-settings-reflector.yml
    - name: Config Settings all - Visual Studio Code
      ansible.builtin.import_tasks: tasks/basic_all/config_all-settings-VSCode.yml
    - name: Config Settings all - Ulauncher extensions
      ansible.builtin.import_tasks: tasks/basic_all/config_all-settings-ulauncher-extensions.yml
    - name: Config Settings all - Cron
      ansible.builtin.import_tasks: tasks/basic_all/config_all-settings-cron.yml
    #
    # # Services and cronjobs:
    # - name: Config cronjobs all - cronjobs - ClamAV
    #   ansible.builtin.import_tasks: tasks/basic_all/config_all-cronjobs-ClamAV.yml
    #   - replaced by systemd timer
    - name: Config Services all - ArchPacStuff
      ansible.builtin.import_tasks: tasks/basic_all/config_all-services-ArchPacStuff.yml
    - name: Config Services all - cron
      ansible.builtin.import_tasks: tasks/basic_all/config_all-services-cron.yml
    - name: Config Services all - ClamAV
      ansible.builtin.import_tasks: tasks/basic_all/config_all-services-ClamAV.yml
    - name: Config Services all - Printing CUPS
      ansible.builtin.import_tasks: tasks/basic_all/config_all-services-pintingCups.yml
    - name: Config Services all - SSH
      ansible.builtin.import_tasks: tasks/basic_all/config_all-services-ssh.yml
    - name: Config Services all - Starship shell prompt
      ansible.builtin.import_tasks: tasks/basic_all/config_all-services-starship.yml
    - name: Config Services all - zsh plugins
      ansible.builtin.import_tasks: tasks/basic_all/config_all-services-zshPlugins.yml
    - name: Config Services all - Syncthing
      ansible.builtin.import_tasks: tasks/basic_all/config_all-services-syncthing.yml
    - name: Config Services all - misc (system + user)
      ansible.builtin.import_tasks: tasks/basic_all/config_all-services-misc.yml
    #
    # ----------------------------------------------------------
    # ### Virtualisierung:
    - name: VM - Qemu KVM
      ansible.builtin.import_tasks: tasks/VM/packages_workstation-VM-QemuKvm.yml
    - name: VM - daemon
      ansible.builtin.import_tasks: tasks/VM/config_all-VM-daemon.yml
    - name: VM - users
      ansible.builtin.import_tasks: tasks/VM/config_all-VM-users.yml
    - name: VM - create
      ansible.builtin.import_tasks: tasks/VM/config_all-VM-QemuKvm-create.yml
    #
    # ----------------------------------------------------------
    # ### Create Users / Config User privileges:
    - name: Config users
      ansible.builtin.import_tasks: tasks/basic_all/config_all-users.yml
    #
    # ----------------------------------------------------------
    # ### Mail:
    # Nur lokaler Mailversand bei Start/Ende Scan + VirusEvent von ClamAV
    - name: Install packages for (local) mail
      ansible.builtin.import_tasks: tasks/basic_all/packages_all-mail.yml
    - name: Config postfix
      ansible.builtin.import_tasks: tasks/basic_all/config_all-mail.yml
    - name: Config postfix.service
      ansible.builtin.import_tasks: tasks/basic_all/config_all-mail-service.yml
    - name: Initial test mail
      ansible.builtin.import_tasks: tasks/basic_all/config_all-mail-testmail.yml
    #
    # ----------------------------------------------------------
    # ### Python:
    - name: Python Packages
      ansible.builtin.import_tasks: tasks/basic_all/packages_workstation-python.yml
    - name: Config Settings all - python - uv
      ansible.builtin.import_tasks: tasks/basic_all/config_all-settings-python-uv.yml
    - name: Python Env
      ansible.builtin.import_tasks: tasks/basic_all/packages_workstation-pythonEnv.yml
    - name: Pip and Pipx install
      ansible.builtin.import_tasks: tasks/basic_all/packages_workstation-pythonPip.yml
    #
    # ----------------------------------------------------------
    # ### C/C++:
    - name: C/C++ packages
      ansible.builtin.import_tasks: tasks/basic_all/packages_workstation-cpp.yml
    #
    # ----------------------------------------------------------
    # ### NVM / Node.js:
    - name: NVM Node.js packages
      ansible.builtin.import_tasks: tasks/basic_all/packages_workstation-nvmNodejs.yml
    #
    # ----------------------------------------------------------
    # ### Docker:
    - name: Docker repo
      ansible.builtin.import_tasks: tasks/basic_all/config_workstation-docker-repo.yml
    - name: Docker packages
      ansible.builtin.import_tasks: tasks/basic_all/packages_workstation-docker.yml
    - name: Docker config
      ansible.builtin.import_tasks: tasks/basic_all/config_workstation-docker.yml
    - name: Docker service
      ansible.builtin.import_tasks: tasks/basic_all/config_workstation-docker-services.yml
    #
    # ----------------------------------------------------------
    # ### Ansible galaxy collections:
    - name: Install ansbile collections via ansible-galaxy
      ansible.builtin.import_tasks: tasks/basic_all/packages_workstation-ansibleGalaxyCollections.yml
    # ----------------------------------------------------------

- name: Genome Shell Extension + Desktop Settings
  hosts: localhost
  connection: local
  become: true
  become_user: "{{ env_user }}"
  tasks:
    - name: Config Gnome Desktop Preferences
      ansible.builtin.import_tasks: tasks/Desktop_Gnome/config_workstation-Gnome-DesktopPreferences.yml

- name: Cleanup
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Cleanup package cache + orphaned packages (incl. flatpak)
      ansible.builtin.import_tasks: tasks/basic_all/all_cleanup.yml

- name: Write Final Message
  hosts: localhost
  connection: local
  become: true
  become_user: "{{ env_user }}"
  tasks:
    - name: Write Final Message
      ansible.builtin.debug:
        msg: "Please restart the system for the changes to take effect!"

# - name: Reboot system
#   hosts: localhost
#   connection: local
#   become: true
#   tasks:
#     - name: RebootSystem
#       ansible.builtin.import_tasks: tasks/basic_all/all_reboot.yml
#       # da hier local/pull --> geht nicht
#       # FAILED! => {"changed": false, "elapsed": 0, "msg": "Running reboot with local connection would reboot the control node.", "rebooted": false}
