---

- hosts: localhost
  connection: local
  become: no
  tags: always,pre,ansibleFacts
  gather_facts: true
  pre_tasks:
  - include: tasks/basic_all/config_workstation-ansibleFacts.yml


- hosts: localhost
  connection: local
  become: true
  tags: always,pre
  pre_tasks:
  - include: tasks/basic_all/config_workstation-addrepos.yml
  - include: tasks/fix/config_workstation-addrepos-ubuntu-fix.yml
  - include: tasks/basic_all/all_update.yml


- hosts: localhost
  connection: local
  become: true
  tags: always
  tasks:
  # ### Entfernen nicht benötigter, vorinstallierter Pakete:
  - include: tasks/Desktop_Gnome/packages_workstation-Gnome-removePreInstalls.yml
  - include: tasks/Desktop_Plasma/packages_workstation-Plasma-removePreInstalls.yml
  # ----------------------------------------------------------
  # ### Installation Software-Packages (inklusive snap + flatpak):
  # - repo:
  - include: tasks/basic_all/packages_workstation-basic.yml
  - include: tasks/Desktop_Gnome/packages_workstation-Gnome.yml
  - include: tasks/Desktop_Plasma/packages_workstation-Plasma.yml
  # - gnomeshell:
  - include: tasks/Desktop_Gnome/packages_workstation-gnomeshellstuff.yml
  # - flatpak:
  - include: tasks/flatpakSnap/config_workstation-flatpak.yml
  - include: tasks/flatpakSnap/packages_workstation-flatpak.yml
    # - snap:
  - include: tasks/flatpakSnap/config_workstation-snap.yml
  - include: tasks/flatpakSnap/packages_workstation-snap.yml
  # - Suse - Multimedia:
  #- include: tasks/basic_all/config_workstation-addrepos-suseMultimedia.yml
  - include: tasks/basic_all/packages_workstation-suseMultimedia.yml
  # Installation lokal heruntergeladener Pakete:
  - include: tasks/basic_all/packages_workstation-localPackageInstall.yml
  # ----------------------------------------------------------
  # ### Config Firewall, Services, sonstige Settings:
  - include: tasks/basic_all/config_all-firewall.yml
  - include: tasks/basic_all/config_workstation-firewall.yml
  - include: tasks/basic_all/config_all-services-misc.yml
  - include: tasks/basic_all/config_all-settings-misc.yml
  # ----------------------------------------------------------
  # ### Virtualisierung:
  - include: tasks/VM/packages_workstation-VM-QemuKvm.yml
  - include: tasks/VM/config_all-VM-daemon.yml
  - include: tasks/VM/config_all-VM-users.yml
  - include: tasks/VM/config_all-VM-QemuKvm-create.yml
  # ----------------------------------------------------------
  # ### sudo-ansible-user + cronjob:
  #- include: tasks/basic_all/config_all-ansible-users.yml
  #- include: tasks/basic_all/config_all-cron.yml
  # ----------------------------------------------------------
  # ### cleanup:
  - include: tasks/basic_all/all_cleanup.yml


- hosts: localhost
  connection: local
  #become: false
  become_user: "{{ env_user }}"
  tags: always,gnome
  tasks:
  #- include: tasks/Desktop_Gnome/packages_workstation-Gnome-GnomeshellExtensions.yml
  #- include: tasks/Desktop_Gnome/config_workstation-Gnome-GnomeshellExtensions.yml
  - include: tasks/Desktop_Gnome/config_workstation-Gnome-DesktopPreferences.yml

  - debug:
      msg: "Please restart the system for the changes to take effect!"


#- hosts: localhost
#  connection: local
#  become: true
#  tags: always,reboot
#  tasks:
#  - include: tasks/basic_all/all_reboot.yml # da hier local/pull --> geht nicht
# fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 0, "msg": "Running reboot with local connection would reboot the control node.", "rebooted": false}

### "all_reboot.yml" geändert auf ansible.builtin.shell, cmd: reboot
### (und damit nicht mehr reboot über ansible-Modul (s.o.))
#- hosts: localhost
#  connection: local
#  become: true
#  tags: always,reboot
#  tasks:
#  - include: tasks/basic_all/all_reboot.yml
