---

#   ssh, ansible + Voraussetungen/Abhängigkeiten, git ... muss bereits vorhanden sein

- hosts: localhost
  connection: local
  become: no
  tags: always,pre,ansibleFacts
  gather_facts: true
  pre_tasks:
  - include: tasks/config_workstation-getFacts.yml


- hosts: localhost
  connection: local
  become: true
  tags: always,pre
  pre_tasks:
    - include: tasks/config_workstation-addrepos.yml
    - include: tasks/all_update.yml


- hosts: localhost
  connection: local
  become: true
  tags: always
  tasks:
  - include: tasks/packages_workstation-remove-PreInstalls.yml
  - include: tasks/packages_workstation-basic.yml
  - include: tasks/packages_workstation-DEspecific.yml
  - include: tasks/packages_workstation-additional.yml
  - include: tasks/config_workstation-snap.yml
  - include: tasks/packages_workstation-snap.yml
  - include: tasks/config_workstation-flatpak.yml
  - include: tasks/packages_workstation-flatpak.yml
  - include: tasks/packages_workstation-gnomeshellstuff.yml
  - include: tasks/config_all-firewall.yml
  - include: tasks/config_workstation-firewall.yml
  - include: tasks/config_all-services-misc.yml
# --------------------
# ### Virtualisierung:
  - include: tasks/packages_workstation-VM-QemuKvm.yml
  - include: tasks/config_all-VM-QemuKvm.yml
  - include: tasks/config_all-VM-users.yml
# ----------------------
# ### Suse - Multimedia:
#  - include: tasks/config_workstation-addrepos-suseMultimedia.yml
  - include: tasks/packages_workstation-suseMultimedia.yml
# ---------------------------------
# ### sudo-ansible-user + cronjob:
#  - include: tasks/config_all-ansible-users.yml
#  - include: tasks/config_all-cron.yml
#
# ### cleanup:
  - include: tasks/all_cleanup.yml


- hosts: localhost
  connection: local
  become_user: "{{ env_user }}"
#  become: false
  tags: always,gnome
  tasks:
#  - include: tasks/packages_workstation-gnomeshellExtensions.yml
#  - include: tasks/config_workstation-gnomeshellExtension.yml
  - include: tasks/config_workstation-desktopPreferences.yml

  - debug:
      msg: "Please restart the system for the changes to take effect!"

#- hosts: localhost
#  connection: local
#  become: true
#  tags: always,reboot
#  tasks:
#  - include: tasks/all_reboot.yml # da hier local/pull --> geht nicht
# fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 0, "msg": "Running reboot with local connection would reboot the control node.", "rebooted": false}
