# #############
# ### DistRepos
# #############
- name: Update repository index and update system (apt)
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
  #  when: ansible_os_family == "Debian"
  when:
    - ansible_pkg_mgr == "apt"
  changed_when: false

- name: Update repository index and update system (pacman)
  community.general.pacman:
    update_cache: true
    upgrade: true
  when:
    - ansible_pkg_mgr == "pacman"
#  changed_when: false

# ###########
# ### flatpak
# ###########
- name: Update flatpak packages
  ansible.builtin.command: flatpak update
  when:
    - env_datadirs is defined
    #    - env_datadirs.find("/var/lib/flatpak") != -1
    - env_datadirs.find("/var/lib/flatpak") == true
  changed_when: false

# #########
# ### snaps
# #########
# Snaps come with a built-in automatic update mechanism, whereby snaps are refreshed to a new version whenever there’s a new release in the Snap Store.
# Typically, the refresh occurs four times a day ...
- name: Update snap packages
  ansible.builtin.command: snap refresh
  when:
    - env_path is defined
    - env_path.find("/snap/bin") == true
  changed_when: false
