
##########################################
### bashrc - add additional Paths + Config
### ######################################
# - global wäre: /etc/bash_bashrc

- name: bashrc - check status (User, all)
  ansible.builtin.stat:
    path: "/home/{{ env_user }}/.bashrc"
  register: statBashrcUser

- name: bashrc - create (User, all)
  ansible.builtin.file:
    path: "/home/{{ env_user }}/.bashrc"
    state: touch
  when:
    - ansible_distribution in ["Ubuntu", "Archlinux"]
    - not statBashrcUser.stat.exists
    #oder: - statBashrcUser.stat.exists == false

- name: bashrc - Insert/Update additional paths and config - nvm (User, all)
  ansible.builtin.blockinfile:
    path: "/home/{{ env_user }}/.bashrc"
    backup: yes
    marker: "### {mark} 'nvm' - ANSIBLE MANAGED BLOCK ###"
    block: |
      # --------------------------
      # nvm (Node Version Manager)
      # --------------------------
      # https://github.com/nvm-sh/nvm
      # https://linuxize.com/post/how-to-install-node-js-on-ubuntu-22-04/
      #
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
  when:
    - ansible_distribution in ["Ubuntu", "Archlinux"]

- name: bashrc - Insert/Update additional paths and config - vim (User, all)
  ansible.builtin.blockinfile:
    path: "/home/{{ env_user }}/.bashrc"
    backup: yes
    marker: "### {mark} 'vim' ANSIBLE MANAGED BLOCK ###"
    block: |
      # ------------------------------
      # vim als Standard Editor setzen
      # -------------------------------
      export VISUAL=vim
      export EDITOR="${VISUAL}"
  when:
    - ansible_distribution in ["Ubuntu", "Archlinux"]

- name: bashrc - Insert/Update additional paths and config - user-bin (User, all)
  ansible.builtin.blockinfile:
    path: "/home/{{ env_user }}/.bashrc"
    backup: yes
    marker: "### {mark} 'user-bin' ANSIBLE MANAGED BLOCK ###"
    block: |
      # ------------------------------------------
      # Benutzer-bin Verzeichnis an PATH anhängen:
      # ------------------------------------------
      export PATH=/home/{{ env_user }}/.local/bin:$PATH
  when:
    - ansible_distribution in ["Ubuntu", "Archlinux"]

- name: bashrc - Insert/Update additional paths and config - pyenv (User, Ubuntu)
  ansible.builtin.blockinfile:
    path: "/home/{{ env_user }}/.bashrc"
    backup: yes
    marker: "### {mark} 'pyenv' ANSIBLE MANAGED BLOCK ###"
    block: |
      # -----
      # pyenv
      # -----
      # https://ostechnix.com/pyenv-python-version-management-made-easier/
      #
      export PATH="$HOME/.pyenv/bin:$PATH"
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
  when:
    - ansible_distribution in ["Ubuntu"]

#- name: bashrc - initial command 'pyenv init' - pyenv (User, Arch)
#  become: true
#  become_user: "{{ env_user }}"
#  ansible.builtin.shell:
#    cmd: pyenv init >/dev/null && touch /home/{{ env_user }}/.pyenvinitExecuted
 # args:
#    creates: /home/{{ env_user }}/.pyenvinitExecuted
#  ignore_errors: true
#  when:
#    - ansible_distribution in ["Archlinux"]

- name: bashrc - Insert/Update additional paths and config - pyenv (User, Arch)
  ansible.builtin.blockinfile:
    path: "/home/{{ env_user }}/.bashrc"
    backup: yes
    marker: "### {mark} 'pyenv' ANSIBLE MANAGED BLOCK ###"
    block: |
      # -----
      # pyenv
      # -----
      export PYENV_ROOT="$HOME/.pyenv"
      command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
  when:
    - ansible_distribution in ["Archlinux"]


- name: bashrc - check status (root, all)
  ansible.builtin.stat:
    path: "/root/.bashrc"
  register: statBashrcRoot

- name: bashrc - create (root, all)
  ansible.builtin.file:
    path: "/root/.bashrc"
    state: touch
  when:
    - ansible_distribution in ["Ubuntu", "Archlinux"]
    - not statBashrcRoot.stat.exists

- name: bashrc - Insert/Update additional paths and config (root, all)
  ansible.builtin.blockinfile:
    path: "/root/.bashrc"
    backup: yes
    marker: "### {mark} 'vim' ANSIBLE MANAGED BLOCK ###"
    block: |
      # ------------------------------
      # vim als Standard Editor setzen
      # -------------------------------
      export VISUAL=vim
      export EDITOR="${VISUAL}"
  when:
    - ansible_distribution in ["Ubuntu", "Archlinux"]



#######################################
### zsh - add additional Paths + Config
### ###################################
# - global wäre: /etc/zshrc   # https://linuxconfig.org/zsh-shell-installation-and-configuration-on-linux

- name: zshrc - check status (User, all)
  ansible.builtin.stat:
    path: "/home/{{ env_user }}/.zshrc"
  register: statzshrcUser

- name: zshrc - create (User, all)
  ansible.builtin.file:
    path: "/home/{{ env_user }}/.zshrc"
    state: touch
  when:
    - ansible_distribution in ["Ubuntu", "Archlinux"]
    - not statzshrcUser.stat.exists
    #oder: - statzshrcUser.stat.exists == false

- name: zshrc - Insert/Update additional paths and config - nvm (User, all)
  ansible.builtin.blockinfile:
    path: "/home/{{ env_user }}/.zshrc"
    backup: yes
    marker: "### {mark} 'nvm' - ANSIBLE MANAGED BLOCK ###"
    block: |
      # --------------------------
      # nvm (Node Version Manager)
      # --------------------------
      # https://github.com/nvm-sh/nvm
      # https://linuxize.com/post/how-to-install-node-js-on-ubuntu-22-04/
      #
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
  when:
    - ansible_distribution in ["Ubuntu", "Archlinux"]

- name: zshrc - Insert/Update additional paths and config - vim (User, all)
  ansible.builtin.blockinfile:
    path: "/home/{{ env_user }}/.zshrc"
    backup: yes
    marker: "### {mark} 'vim' ANSIBLE MANAGED BLOCK ###"
    block: |
      # ------------------------------
      # vim als Standard Editor setzen
      # -------------------------------
      export VISUAL=vim
      export EDITOR="${VISUAL}"
  when:
    - ansible_distribution in ["Ubuntu", "Archlinux"]

- name: zshrc - Insert/Update additional paths and config - user-bin (User, all)
  ansible.builtin.blockinfile:
    path: "/home/{{ env_user }}/.zshrc"
    backup: yes
    marker: "### {mark} 'user-bin' ANSIBLE MANAGED BLOCK ###"
    block: |
      # ------------------------------------------
      # Benutzer-bin Verzeichnis an PATH anhängen:
      # ------------------------------------------
      export PATH=/home/{{ env_user }}/.local/bin:$PATH
  when:
    - ansible_distribution in ["Ubuntu", "Archlinux"]

- name: zshrc - Insert/Update additional paths and config - pyenv (User, Ubuntu)
  ansible.builtin.blockinfile:
    path: "/home/{{ env_user }}/.zshrc"
    backup: yes
    marker: "### {mark} 'pyenv' ANSIBLE MANAGED BLOCK ###"
    block: |
      # -----
      # pyenv
      # -----
      # https://ostechnix.com/pyenv-python-version-management-made-easier/
      #
      export PATH="$HOME/.pyenv/bin:$PATH"
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
  when:
    - ansible_distribution in ["Ubuntu"]

#- name: zshrc - initial command 'pyenv init' - pyenv (User, Arch)
#  become: true
#  become_user: "{{ env_user }}"
#  ansible.builtin.shell:
#    cmd: pyenv init >/dev/null && touch /home/{{ env_user }}/.pyenvinitExecuted
#  args:
#    creates: /home/{{ env_user }}/.pyenvinitExecuted
#  ignore_errors: true
#  when:
#    - ansible_distribution in ["Archlinux"]

- name: zshrc - Insert/Update additional paths and config - pyenv (User, Arch)
  ansible.builtin.blockinfile:
    path: "/home/{{ env_user }}/.zshrc"
    backup: yes
    marker: "### {mark} 'pyenv' ANSIBLE MANAGED BLOCK ###"
    block: |
      # -----
      # pyenv
      # -----
      export PYENV_ROOT="$HOME/.pyenv"
      command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
  when:
    - ansible_distribution in ["Archlinux"]


- name: zshrc - check status (root, all)
  ansible.builtin.stat:
    path: "/root/.zshrc"
  register: statBashrcRoot

- name: zshrc - create (root, all)
  ansible.builtin.file:
    path: "/root/.zshrc"
    state: touch
  when:
    - ansible_distribution in ["Ubuntu", "Archlinux"]
    - not statBashrcRoot.stat.exists

- name: zshrc - Insert/Update additional paths and config (root, all)
  ansible.builtin.blockinfile:
    path: "/root/.zshrc"
    backup: yes
    marker: "### {mark} 'vim' ANSIBLE MANAGED BLOCK ###"
    block: |
      # ------------------------------
      # vim als Standard Editor setzen
      # -------------------------------
      export VISUAL=vim
      export EDITOR="${VISUAL}"
  when:
    - ansible_distribution in ["Ubuntu", "Archlinux"]



# #######
# ### vim
# #######

# ----------------
# ### VIM Settings

# alt:
#- name: set vim config for user "sandro" (.vimrc) (all)
#  ansible.builtin.script: "{{ env_PWD }}/tasks/config_all-settings-misc-vim.sh"
#  args:
#    creates: "/home/{{ env_user }}/.vimrc"


- name: Set vim global config (ubuntu)
  ansible.builtin.blockinfile:
    path: "/etc/vim/vimrc.local"
    backup: yes
    marker: '" ### {mark} ANSIBLE MANAGED BLOCK ###'
    block: |
      " #
      " Vim5 and later versions support syntax highlighting.
      syntax on

      " If using a dark background within the editing area and syntax highlighting
      " turn on this option as well
      set background=dark

      " The following are commented out as they cause vim to behave a lot
      " differently from regular Vi. They are highly recommended though.
      set showcmd			" Show (partial) command in status line.
      set showmatch		" Show matching brackets.
      set ignorecase		" Do case insensitive matching
      set smartcase		" Do smart case matching
      set incsearch		" Incremental search
      set autowrite		" Automatically save before commands like :next and :make
      set hidden			" Hide buffers when they are abandoned
      set mouse=a			" Enable mouse usage (all modes)

      " weitere Settings:
      colorscheme koehler
      set number			" Show line numbers
      set ruler			" Show row and column ruler information
      " set list
      set nocompatible
      set tabstop=4		" show existing tab with 4 spaces width
      set shiftwidth=4	" Number of auto-indent spaces; when indentig with '>', use 4 spaces
      " set expandtab		" On pressing tab, insert spaces
      set hlsearch		" Highlight all search results
      set undolevels=1000	" Number of undo levels
      " #
  when:
    - ansible_distribution == "Ubuntu"


- name: Set vim global config (arch)
  ansible.builtin.blockinfile:
    path: "/etc/vimrc"
    backup: yes
    marker: '" ### {mark} ANSIBLE MANAGED BLOCK ###'
    block: |
      " #
      " Vim5 and later versions support syntax highlighting.
      syntax on

      " If using a dark background within the editing area and syntax highlighting
      " turn on this option as well
      set background=dark

      " The following are commented out as they cause vim to behave a lot
      " differently from regular Vi. They are highly recommended though.
      set showcmd			" Show (partial) command in status line.
      set showmatch		" Show matching brackets.
      set ignorecase		" Do case insensitive matching
      set smartcase		" Do smart case matching
      set incsearch		" Incremental search
      set autowrite		" Automatically save before commands like :next and :make
      set hidden			" Hide buffers when they are abandoned
      set mouse=a			" Enable mouse usage (all modes)

      " weitere Settings:
      colorscheme koehler
      set number			" Show line numbers
      set ruler			" Show row and column ruler information
      " set list
      set nocompatible
      set tabstop=4		" show existing tab with 4 spaces width
      set shiftwidth=4	" Number of auto-indent spaces; when indentig with '>', use 4 spaces
      " set expandtab		" On pressing tab, insert spaces
      set hlsearch		" Highlight all search results
      set undolevels=1000	" Number of undo levels
      " #
  when:
    - ansible_distribution == "Archlinux"



# ---------------
# ### VIM plugins

# - https://github.com/dense-analysis/ale
- name: Create folder for vim git-plugins (all)
  become: true
  become_user: "{{ env_user }}"
  ansible.builtin.shell:
    cmd: mkdir -p /home/{{ env_user }}/.vim/pack/git-plugins/start
  args:
    creates: /home/{{ env_user }}/.vim/pack/git-plugins/start

- name: Install (git clone) vim plugin - Linter ALE (all)
  become: true
  become_user: "{{ env_user }}"
  ansible.builtin.git:
    repo: https://github.com/dense-analysis/ale.git
    dest: /home/{{ env_user }}/.vim/pack/git-plugins/start
    depth: 1
    update: true
    clone: true



###################################
### Visual Studio Code / Code - OSS
###################################

- name: Install 'Visual Studio Code' bzw 'Code-OSS' - Extension 'Sync Settings' by zokugun (Ubuntu)
  tags: workstation,ubuntu
  ansible.builtin.shell:
    cmd: code --install-extension zokugun.sync-settings
  become: true
  become_user: "{{ env_user }}"
  when:
    - ansible_distribution in ["Ubuntu"]   # hat unter Arch (mit ' Code - OSS') nicht funktioniert

- name: Start 'Visual Studio Code' bzw 'Code-OSS' (Ubuntu)
  tags: workstation,ubuntu
  ansible.builtin.shell:
    cmd: code >/dev/null 2>&1 &  # damit im Home-Verzeichnis der Config-Pfad von VS Code erstellt wird + später die settings.yml dorthin kopiert werden kann
  args:
      creates: /home/{{ env_user }}/.config/Code/User/globalStorage/zokugun.sync-settings/settings.yml   # nur ausführen, wenn nicht bereits z.B. in vorhergehendem Lauf gestartet/erstellt wurde
  become: true
  become_user: "{{ env_user }}"
  when:
    - ansible_distribution in ["Ubuntu"]

- name: Start 'Code - OSS' (Arch)
  tags: workstation,arch
  ansible.builtin.shell:
    cmd: code >/dev/null 2>&1 &  # damit im Home-Verzeichnis der Config-Pfad von VS Code erstellt wird + später die settings.yml dorthin kopiert werden kann
  args:
      creates: "/home/{{ env_user }}/.config/Code - OSS/User/globalStorage/zokugun.sync-settings/settings.yml"   # nur ausführen, wenn nicht bereits z.B. in vorhergehendem Lauf gestartet/erstellt wurde
  become: true
  become_user: "{{ env_user }}"
  when:
    - ansible_distribution in ["Archlinux"]

- name: Wait until 'Visual Studio Code' Extension 'Sync Settings' Standard Config-File is present before continuing (Ubuntu)
  ansible.builtin.wait_for:
    path: /home/{{ env_user }}/.config/Code/User/globalStorage/zokugun.sync-settings/settings.yml   #Datei
    #path: /home/{{ env_user }}/.config/Code/User/globalStorage/zokugun.sync-settings/               # Ordner
  when:
    - ansible_distribution == "Ubuntu"

## da sich die Extension unter Arch nicht so installieren lässt (s.o.) kann dies wegfallen:
#- name: Wait until 'Code - OSS' Extension 'Sync Settings' Standard Config-File is present before continuing (Arch)
#  ansible.builtin.wait_for:
#    path: "/home/{{ env_user }}/.config/Code - OSS/User/globalStorage/zokugun.sync-settings/settings.yml"   # Datei
#    #path: /home/{{ env_user }}/.config/Code/User/globalStorage/zokugun.sync-settings/               # Ordner
#  when:
#    - ansible_distribution == "Archlinux"

## da sich die Extension unter Arch nicht so installieren lässt: Verzeichnis der Extension manuell erstellen,
## damit unten die config-datei dorthin kopiert werden kann
- name: Erstelle hilfsweise manuell 'Sync Settings' Extension Ordner für 'Code - OSS' (Arch)
  tags: workstation,arch
  ansible.builtin.file:
    path: "/home/{{ env_user }}/.config/Code - OSS//User/globalStorage/zokugun.sync-settings"
    state: directory
    mode: '0775'
  become: true
  become_user: "{{ env_user }}"
  when:
    - ansible_distribution in ["Archlinux"]


#- name: Close Visual Studio Code (Ubuntu)
#  tags: workstation,ubuntu
#  ansible.builtin.shell:
#    cmd: pkill -15 code   # Signal: "-15" entspricht "SIGTERM" : Abschließen und beenden des Programms
#    #cmd: killall code
#  become: true
#  become_user: "{{ env_user }}"
#  when:
#    - ansible_distribution == "Ubuntu"

- name: Set/Copy 'Visual Studio Code' settings-file for Extension 'Sync Settings' (Ubuntu)
  tags: workstation,ubuntu
  ansible.builtin.copy:
    src: ./files/VSCode_Extension_Sync-Settings_settings.yml
    dest: /home/{{ env_user }}/.config/Code/User/globalStorage/zokugun.sync-settings/settings.yml   # Pfad bei Install des VS Code deb-Pakets (nicht bei flatpakod oder snap)
    owner: "{{ env_user }}"
    group: "{{ env_user }}"
    mode: u=rw
  when:
    - ansible_distribution == "Ubuntu"

- name: Set/Copy 'Code - OSS' settings-file for Extension 'Sync Settings' (Arch)
  tags: workstation,arch
  ansible.builtin.copy:
    src: ./files/VSCode_Extension_Sync-Settings_settings.yml
    dest: "/home/{{ env_user }}/.config/Code - OSS//User/globalStorage/zokugun.sync-settings/settings.yml"   # Pfad bei Install des VS Code deb-Pakets (nicht bei flatpakod oder snap)
    owner: "{{ env_user }}"
    group: "{{ env_user }}"
    mode: u=rw
  when:
    - ansible_distribution == "Archlinux"
