# #############
# ### s_ansible
# #############

# - name: Config all users - add ansible user (all)
#  ansible.builtin.user:
#    name: s_ansible
#    system: true

# - name: Config all users - s_ansible - set up sudo (all)
#  ansible.builtin.copy:
#    src: files/sudoer_s_ansible
#    dest: /etc/sudoers.d/s_ansible
#    owner: root
#    group: root
#    mode: 0440

# ##########
# ### clamav
# ##########

# https://wiki.archlinux.org/title/ClamAV
- name: Config all users - clamav - allow running notify-send and mail (all)
  ansible.builtin.blockinfile:
    path: "/etc/sudoers.d/clamav"
    create: true
    owner: root
    group: root
    mode: "0440"
    backup: false
    marker: "# ### {mark} ANSIBLE MANAGED BLOCK - clamav ###"
    block: |
      clamav ALL = (ALL) NOPASSWD: SETENV: /usr/bin/notify-send, /usr/bin/mail
  # when:
  #   - ansible_distribution in ["Archlinux", "Debian"]

  # ############################
  # ### set zsh as default shell
  # ############################
  # https://stackoverflow.com/questions/43560657/edit-current-users-shell-with-ansible
- name: Config all users - env_user - set zsh as standard shell (all)
  ansible.builtin.shell: "usermod --shell $(which zsh) {{ env_user }}"
  # when:
  #   - ansible_distribution in ["Archlinux", "Debian"]
