# #############
# ### Archlinux
# #############

# multilib: If you want to run 32 bit applications on your x86_64 system... # e.g. for 'steam'
- name: Config Workstation addrepos - pacman.conf - activate multilib repo - check status flagfile (Archlinux)
  ansible.builtin.stat:
    path: "/home/{{ env_user }}/.ansible_addrepoMultilib"
  register: addrepomultilib

- name: Config Workstation addrepos - pacman.conf - activate multilib repo - step1 (Archlinux)
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/pacman.conf"
    regexp: "^#Include = /etc/pacman.d/mirrorlist"
    insertafter: '^#\[multilib\]'
    line: "Include = /etc/pacman.d/mirrorlist"
  when:
    - ansible_facts['distribution'] == "Archlinux"
    - not addrepomultilib.stat.exists

- name: Config Workstation addrepos - pacman.conf - activate multilib repo - step2 (Archlinux)
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/pacman.conf"
    regexp: '^#\[multilib\]'
    line: "[multilib]"
    backup: true
  when:
    - ansible_facts['distribution'] == "Archlinux"
    - not addrepomultilib.stat.exists

# modify /etc/pacman.d/mirrorlist to activate repo multilib needs to be done only once
- name: Config Workstation addrepos - pacman.conf - activate multilib repo - create flagfile (Archlinux)
  become: true
  become_user: "{{ env_user }}"
  ansible.builtin.command:
    cmd: "touch /home/{{ env_user }}/.ansible_addrepoMultilib"
  args:
    creates: "/home/{{ env_user }}/.ansible_addrepoMultilib"
  when:
    - ansible_facts['distribution'] == "Archlinux"
    - not addrepomultilib.stat.exists
