# ##########
# ### system
# ##########

# ----------
# ### ClamAV
# ----------
- name: Systemd - create service unit - update ClamAV database (all)
  ansible.builtin.blockinfile:
    path: "/etc/systemd/system/clamav-updatedb.service"
    backup: true
    marker: "### {mark} 'Update ClamAV database - service unit' ANSIBLE MANAGED BLOCK ###"
    block: |
      [Unit]
      Description=Update ClamAV database hourly
      Wants=network-online.target
      After=network-online.target


      [Service]
      Type=oneshot
      ExecStart=/usr/bin/freshclam --quiet
      User=clamav
  when:
    - ansible_distribution in ["Archlinux", "Ubuntu"]

- name: Systemd - create timer unit - update ClamAV database (all)
  ansible.builtin.blockinfile:
    path: "/etc/systemd/system/clamav-updatedb.timer"
    backup: true
    marker: "### {mark} 'Update ClamAV database - timer unit' ANSIBLE MANAGED BLOCK ###"
    block: |
      [Unit]
      Description=Update ClamAV database hourly

      [Timer]
      # starts service (unit): clamav-updatedb.service
      Unit=clamav-updatedb.service
      OnCalendar=hourly
      RandomizedDelaySec=10min
      Persistent=true
  when:
    - ansible_distribution in ["Archlinux", "Ubuntu"]

- name: Systemd - update ClamAV database - enable+start timer (all)
  ansible.builtin.systemd:
    name: clamav-updatedb.timer
    state: started
    enabled: true
    daemon_reload: true
  when:
    - ansible_distribution in ["Archlinux", "Ubuntu"]


# ########
# ### user
# ########

# --- no systemd user instance timer/service yet
