# ###########
# ### UFW ###
# ###########
# # Info: ufw in install script bereits gesatartet + enabled

# ### UFW - allow
- name: UFW - allow KDE Connect / GSConnect (tcp) (Ubuntu)
  community.general.ufw:
    rule: allow
    port: 1714:1764
    proto: tcp
    comment: KDE Connect / GSConnect
  when: ansible_distribution == "Ubuntu"
  register: firewall_ufw

- name: UFW - allow KDE Connect / GSConnect (udp) (Ubuntu)
  community.general.ufw:
    rule: allow
    port: 1714:1764
    proto: udp
    comment: KDE Connect / GSConnect
  when: ansible_distribution == "Ubuntu"
  register: firewall_ufw

# ### UFW - reload
- name: UFW - reload (Ubuntu)
  community.general.ufw:
    state: reloaded
  when: ansible_distribution == "Ubuntu" and
    firewall_ufw.changed

# #################
# ### firewalld ###
# #################
# Info: firewalld.service in install script bereits gesatartet + enabled

# Requirements für ansible.posix.firewalld Modul: firewalld >= 0.2.11 und python-firewall >= 0.2.11
- name: Firewalld - allow KDE Connect (Archlinux)
  ansible.posix.firewalld:
    service: kdeconnect
    permanent: true
    state: enabled
    immediate: true
  when: ansible_distribution in ["Archlinux"]
  register: firewall_d

# - name: Firewalld - allow KDE Connect (Archlinux)
#   become: true
#   ansible.builtin.shell:
#     cmd: firewall-cmd --permanent --add-service kdeconnect
#   when: ansible_distribution in ["Archlinux"]

- name: Firewalld - reload (Archlinux)
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  when:
    - ansible_distribution in ["Archlinux"]
    - firewall_d.changed
