# #####################
# ### Docker - services
# #####################

# activate docker.service only when using very frequently, on server, ...
# - name: Docker - services - enable and start docker.service (all)
#   become: true
#   ansible.builtin.service:
#     name: docker.service
#     enabled: true
#     state: started

- name: Docker - services - enable and start docker.socket (all)
  become: true
  ansible.builtin.service:
    name: docker.socket
    enabled: true
    state: started

# ---
# --- Rootless mode
# ---

# - Archlinux:
#
# - name: Docker - services - make sure systemd User-folder exists (env_user) (Arch)
#   become: true
#   become_user: "{{ env_user }}"
#   ansible.builtin.file:
#     path: "/home/{{ env_user }}/.config/systemd/user"
#     state: directory
#     owner: "{{ env_user }}"
#     group: "{{ env_user }}"
#     mode: '0755'
#   when: ansible_facts['distribution'] == "Archlinux"

# - name: Docker - services - aktivate and start docker.socket - scope user (env_user) (Arch)
#   become: true
#   become_user: "{{ env_user }}"
#   ansible.builtin.systemd_service:
#     name: docker.socket
#     scope: user
#     state: started
#     enabled: true
#   # environment:
#   #   XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts.getent_passwd[env_user][1] }}"
#   #   DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_facts.getent_passwd[env_user][1] }}/bus"
#   when: ansible_facts['distribution'] == "Archlinux"
