# ###########
# ### UFW ###
# ###########

# ### UFW - allow
- name: UFW - allow KDE Connect / GSConnect (tcp) (Ubuntu)
  community.general.ufw:
    rule: allow
    port: 1714:1764
    proto: tcp
    comment: KDE Connect / GSConnect
  when: ansible_distribution == "Ubuntu"
  register: firewall_ufw

- name: UFW - allow KDE Connect / GSConnect (udp) (Ubuntu)
  community.general.ufw:
    rule: allow
    port: 1714:1764
    proto: udp
    comment: KDE Connect / GSConnect
  when: ansible_distribution == "Ubuntu"
  register: firewall_ufw

# ### UFW - reload
- name: UFW - reload (Ubuntu)
  community.general.ufw:
    state: reloaded
  when: ansible_distribution == "Ubuntu" and
        firewall_ufw.changed


# #################
# ### firewalld ###
# #################

- name: Firewalld - allow KDE Connect (Archlinux,Suse)
  ansible.posix.firewalld:
    service: kdeconnect
    permanent: true
    state: enabled
    immediate: true
  when: ansible_distribution in ["Archlinux"] or
        ansible_os_family == "Suse"
  register: firewall_d

- name: Firewalld - reload (Archlinux)
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  when: (ansible_distribution in ["Archlinux"] or
        ansible_os_family == "Suse") and
        firewall_d.changed
