
- name: AnsibleFacts - Get desktop environment (XDG_CURRENT_DESKTOP)
  set_fact:
    env_desktop: "{{ ansible_facts['env']['XDG_CURRENT_DESKTOP']|lower }}"   # z.B. "ubuntu:GNOME"
#    env_desktop: "{{ lookup('env','XDG_CURRENT_DESKTOP')|lower }}"
    env_hostname: "{{ ansible_facts['hostname'] }}"

- name: AnsibleFacts - Get display server (XDG_SESSION_TYPE)
  set_fact:
    env_displayserver: "{{ ansible_facts['env']['XDG_SESSION_TYPE']|lower }}"   # z.B. "x11"
  when:
    - ansible_distribution == "Ubuntu"

- name: AnsibleFacts - Get datadirs (XDG_DATA_DIRS)
  # In Archlinux/KDE anscheinend nicht vorhanden
  set_fact:
    env_datadirs: "{{ ansible_facts['env']['XDG_DATA_DIRS'] }}"   # z.B.: "/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop"
  when:
    - ansible_distribution == "Ubuntu"


- name: AnsibleFacts - Get path (PATH)
  set_fact:
    env_path: "{{ ansible_facts['env']['PATH'] }}"   # z.B.: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

- name: AnsibleFacts - Get PWD (PATH)
  set_fact:
    env_PWD: "{{ ansible_facts['env']['PWD'] }}"   # z.B.: "/home/sandro/dev"

- name: AnsibleFacts - Get user (USER)
  set_fact:
    env_user: "{{ ansible_facts['env']['USER'] }}"   # z.B.: "sandro"

- name: AnsibleFacts - Get lsb lsb-release
  set_fact:
    env_lsb: "{{ ansible_facts['lsb']['release'] }}"   # z.B. bei Ubuntu 20.04: "20.04"
    #env_lsbmajor: "{{ ansible_facts['lsb']['major_release'] }}"   # z.B. bei Ubuntu 20.04: "20"

- name: AnsibleFacts - Print variable
  debug:
#    msg: "env_desktop: {{ env_desktop }}"
#    msg: "env_hostname: {{ env_hostname }}"
#    msg: "env_displayserver: {{ env_displayserver }}"
#    msg: "env_datadirs: {{ env_datadirs }}"
#    msg: "env_path: {{ env_path }}"
#    msg: "env_PWD: {{ env_PWD }}"
    msg: "env_user: {{ env_user }}"
#    msg: "env_lsb: {{ env_lsb }}"
#    msg: "env_lsbmajor: {{ env_lsbmajor }}"
