# #########################
# ### starship shell prompt
# #########################
# https://starship.rs/
#
# config: in 'config_all-settings-starship.yml'
# update: via systemd timer

- name: Install Starship via pacman (Arch)
  become: true
  ansible.builtin.package:
    name: starship
    state: present
  when:
    - ansible_facts['distribution'] in ["Archlinux"]

# curl -sS "https://starship.rs/install.sh" >"/home/${userid}/starship_install.sh" && chmod +x "/home/${userid}/starship_install.sh"
# - name: Starship Shell Prompt - Download install script (Arch)
#   ansible.builtin.get_url:
#     url: "https://starship.rs/install.sh"
#     dest: "/home/{{ env_user }}/starship_install.sh"
#     timeout: 300
#     force: false
#     owner: "{{ env_user }}"
#     group: "{{ env_user }}"
#     mode: "0755"
#   when:
#     - ansible_facts['distribution'] in ["Archlinux"]

# - name: Starship Shell Prompt - check installation status in user local bin (Arch)
#   ansible.builtin.stat:
#     path: /usr/local/bin/starship
#   register: starshipbin

# - name: Starship Shell Prompt - create directory '/usr/local/bin' if not exists  (Arch)
#   ansible.builtin.file:
#     path: /usr/local/bin
#     state: directory
#     mode: "0755"
#   when:
#     - ansible_facts['distribution'] in ["Archlinux"]

# - name: Starship Shell Prompt - execute install script (systemwide install) (Arch)
#   become: true
#   # become_user: "{{ env_user }}" # install nach /usr/local/bin, daher nicht als env_user ausführen
#   ansible.builtin.command: "/home/{{ env_user }}/starship_install.sh --yes"
#   args:
#     creates: /usr/local/bin/starship
#   when:
#     - not starshipbin.stat.exists
#     - ansible_facts['distribution'] in ["Archlinux"]
