# ######################
# ### Python pip install
# ######################
# python3-pip, python3-psutil, (python3-pyinotify), ...: Installiert in packages_workstation-basic.yml

# - allgemein:
# - https://pythonspeed.com/articles/externally-managed-environment-pep-668/
# - https://stackoverflow.com/questions/75616371/sudo-pip-install-cryptography-error-externally-managed-environment
# - https://itsfoss.com/externally-managed-environment/#option-2-use-python-virtual-environment
# - https://stackoverflow.com/questions/75608323/how-do-i-solve-error-externally-managed-environment-everytime-i-use-pip3
# - https://stackoverflow.com/questions/75602063/pip-install-r-requirements-txt-is-failing-this-environment-is-externally-manag/75696359#75696359
# - https://peps.python.org/pep-0668/#mark-the-installation-as-externally-managed
#
# pipx: jupyter
# - # jupyter: https://samedwardes.com/blog/2022-10-23-best-jupyter-lab-install/

- name: Install packages - workstation - Python - pip (env_user, all)
  # become: true
  # become_user: "{{ env_user }}"
  ansible.builtin.debug:
    msg: "Wenn es in einem Folgeschritt zu Fehlermelung kommt: Terminal schließen + wieder neu öffnen + nochmal Script/Playbook starten"

# - name: Lade Shell-Umgebung neu (bash oder zsh) für Benutzer {{ env_user }}
#   ansible.builtin.shell: |
#     {% if ansible_facts['shell'] | default(ansible_facts['env']['SHELL']) | basename == 'bash' %}
#       source /home/{{ env_user }}/.bashrc
#     {% elif ansible_facts['shell'] | default(ansible_facts['env']['SHELL']) | basename == 'zsh' %}
#       source /home/{{ env_user }}/.zshrc
#     {% endif %}
#   args:
#     executable: "{{ ansible_facts['shell'] | default(ansible_facts['env']['SHELL']) }}"
#   # become: true
#   # become_user: "{{ env_user }}"
#   register: shell_refresh
#   changed_when: shell_refresh is changed

- name: Install packages - workstation - Python - pip - upgrade pip (env_user, all)
  # become: true
  # become_user: "{{ env_user }}"
  ansible.builtin.command: pip install --upgrade pip
  args:
    creates: "/home/{{ env_user }}/.ansible_PythonPip"

# [ERROR]: Task failed: Module failed: non-zero return code
# Origin: /home/USERID/ansible_workstation/tasks/basic_all/packages_workstation-pythonPip.yml:37:3
# 35 #   changed_when: shell_refresh is changed
# 36
# 37 - name: Install packages - workstation - Python - pip - upgrade pip (env_user, all)
#      ^ column 3
# fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["pip", "install", "--upgrade", "pip"],
# "delta": "0:00:00.236152", "end": "2026-04-10 20:31:45.649753", "msg": "non-zero return code",
# "rc": 1, "start": "2026-04-10 20:31:45.413601", "stderr": "error: externally-managed-environment
# \n\n\C3\97 This environment is externally managed\n\E2\95\B0\E2\94\80> To install Python packages
# system-wide, try 'pacman -S\n    python-xyz', where xyz is the package you are trying to\n
# install.\n    \n    If you wish to install a non-Arch-packaged Python package,\n
# create a virtual environment using 'python -m venv path/to/venv'.\n
# Then use path/to/venv/bin/python and path/to/venv/bin/pip.\n    \n
# If you wish to install a non-Arch packaged Python application,\n
# it may be easiest to use 'pipx install xyz', which will manage a\n
# virtual environment for you. Make sure you have python-pipx\n
# installed via pacman.\n\nnote: If you believe this is a mistake, please contact your Python
# installation or OS distribution provider. You can override this, at the risk of breaking your
# Python installation or OS, by passing --break-system-packages.\nhint: See PEP 668 for the detailed
# specification.", "stderr_lines": ["error: externally-managed-environment", "",
#  "\C3\97 This environment is externally managed", "\E2\95\B0\E2\94\80>
# To install Python packages system-wide, try 'pacman -S", "
# python-xyz', where xyz is the package you are trying to", "    install.", "    ",
# "    If you wish to install a non-Arch-packaged Python package,", "
# create a virtual environment using 'python -m venv path/to/venv'.", "
# Then use path/to/venv/bin/python and path/to/venv/bin/pip.", "    ",
# "    If you wish to install a non-Arch packaged Python application,",
# "    it may be easiest to use 'pipx install xyz', which will manage a",
# "    virtual environment for you. Make sure you have python-pipx",
# "    installed via pacman.", "", "note: If you believe this is a mistake,
# please contact your Python installation or OS distribution provider.
# You can override this, at the risk of breaking your Python installation or OS,
# by passing --break-system-packages.", "hint: See PEP 668 for the detailed specification."],
# "stdout": "", "stdout_lines": []}

# - name: Python - pipx - install apps - with dependencies (all)
#   # become: true
#   # become_user: "{{ env_user }}"
#   community.general.pipx:
#     state: present
#     name: "{{ item }}"
#     install_deps: true
#   loop:
#     # - cst-lsp # -> pip # Zed editor Extension 'zed-python-refactoring'
#     # - ansible # https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html # zurück umgestellt auf inst via paketmanager
#     - jedi-language-server # autocompletion for python (Anmerkung: 'jedi' installed via pip)
#     - jupyter # Jupyter metapackage: notebook jupyterlab ipython ipykernel jupyter-console nbconvert ipywidgets
#     # - python-lsp-server[all] # -> pip # Zed editor Extension 'Python LSP' # Zed editor Extension 'zed-python-refactoring')
#     #   -> sonst: (symlink missing or pointing to unexpected location)

# # https://pipx.pypa.io/stable/installation/#on-linux
# - name: Python - pipx - config - ensurepath (all)
#   # become: true
#   # become_user: "{{ env_user }}"
#   ansible.builtin.shell:
#     cmd: pipx ensurepath

- name: Install packages - workstation - Python - pip - shell install libs - setuptools (all)
  # become: true
  # become_user: "{{ env_user }}"
  ansible.builtin.command:
    cmd: pip install --user setuptools
  args:
    creates: "/home/{{ env_user }}/.ansible_PythonPip"

- name: Install packages - workstation - Python - pip - install libs via builtin shell - python_pip_requirements.txt (all)
  # become: true
  # become_user: "{{ env_user }}"
  ansible.builtin.command:
    cmd: "pip install --user -r {{ playbook_dir }}/files/python_pip_requirements.txt"
  args:
    creates: "/home/{{ env_user }}/.ansible_PythonPip"

- name: Install packages - workstation - Python - pip - set flag file for pip installs (env_user, all)
  # become: true
  # become_user: "{{ env_user }}"
  ansible.builtin.file:
    path: "/home/{{ env_user }}/.ansible_PythonPip"
    state: touch
    modification_time: preserve
    mode: u=rw,g=r,o=r
