# ######################
# ### Python pip install
# ######################
# python3-pip, python3-psutil, (python3-pyinotify), ...: Installiert in packages_workstation-basic.yml

# - allgemein:
# - https://pythonspeed.com/articles/externally-managed-environment-pep-668/
# - https://stackoverflow.com/questions/75616371/sudo-pip-install-cryptography-error-externally-managed-environment
# - https://itsfoss.com/externally-managed-environment/#option-2-use-python-virtual-environment
# - https://stackoverflow.com/questions/75608323/how-do-i-solve-error-externally-managed-environment-everytime-i-use-pip3
# - https://stackoverflow.com/questions/75602063/pip-install-r-requirements-txt-is-failing-this-environment-is-externally-manag/75696359#75696359
# - https://peps.python.org/pep-0668/#mark-the-installation-as-externally-managed
#
# pipx: jupyter
# - # jupyter: https://samedwardes.com/blog/2022-10-23-best-jupyter-lab-install/

- name: Install packages - workstation - Python - pip (env_user, all)
  become: true
  become_user: "{{ env_user }}"
  ansible.builtin.debug:
    msg: "Wenn es in einem Folgeschritt zu Fehlermelung kommt: Terminal schließen + wieder neu öffnen + nochmal Script/Playbook starten"

- name: Install packages - workstation - Python - pip - upgrade pip (env_user, all)
  become: true
  become_user: "{{ env_user }}"
  ansible.builtin.command: pip install --upgrade pip
  args:
    creates: "/home/{{ env_user }}/.ansible_PythonPip"

# - name: Python - pipx - install apps - with dependencies (all)
#   become: true
#   become_user: "{{ env_user }}"
#   community.general.pipx:
#     state: present
#     name: "{{ item }}"
#     install_deps: true
#   loop:
#     # - cst-lsp # -> pip # Zed editor Extension 'zed-python-refactoring'
#     # - ansible # https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html # zurück umgestellt auf inst via paketmanager
#     - jedi-language-server # autocompletion for python (Anmerkung: 'jedi' installed via pip)
#     - jupyter # Jupyter metapackage: notebook jupyterlab ipython ipykernel jupyter-console nbconvert ipywidgets
#     # - python-lsp-server[all] # -> pip # Zed editor Extension 'Python LSP' # Zed editor Extension 'zed-python-refactoring')
#     #   -> sonst: (symlink missing or pointing to unexpected location)

# # https://pipx.pypa.io/stable/installation/#on-linux
# - name: Python - pipx - config - ensurepath (all)
#   become: true
#   become_user: "{{ env_user }}"
#   ansible.builtin.shell:
#     cmd: pipx ensurepath

- name: Install packages - workstation - Python - pip - shell install libs - setuptools (all)
  become: true
  become_user: "{{ env_user }}"
  ansible.builtin.command:
    cmd: pip install --user setuptools
  args:
    creates: "/home/{{ env_user }}/.ansible_PythonPip"

- name: Install packages - workstation - Python - pip - install libs via builtin shell - python_pip_requirements.txt (all)
  become: true
  become_user: "{{ env_user }}"
  ansible.builtin.command:
    cmd: "pip install --user -r {{ playbook_dir }}/files/python_pip_requirements.txt"
  args:
    creates: "/home/{{ env_user }}/.ansible_PythonPip"

- name: Install packages - workstation - Python - pip - set flag file for pip installs (env_user, all)
  become: true
  become_user: "{{ env_user }}"
  ansible.builtin.file:
    path: "/home/{{ env_user }}/.ansible_PythonPip"
    state: touch
    modification_time: preserve
    mode: u=rw,g=r,o=r
