# ###############################
# ### Vicinae - packages
# ### - launcher for your desktop
# ###############################
# - https://github.com/vicinaehq/vicinae

# um via paru zu installieren wird sudo tmp. do konfiguriert, dass die Gruppe wheel kein passwort braucht
# Anmkerung: env_user ist in der Gruppe wheel drin

- name: Install - packages workstation - vicinae - Backup existing wheel sudoers file (Arch)
  tags: upvic
  become: true
  ansible.builtin.copy:
    src: /etc/sudoers.d/wheel
    dest: /etc/sudoers.d/wheel.bak
    remote_src: true
    force: false
    mode: '0640'
    owner: root
    group: root
  when: ansible_facts['distribution'] in ["Archlinux"]

- name: Install - packages workstation - vicinae - Configure passwordless sudo for wheel group (Arch)
  tags: upvic
  become: true
  ansible.builtin.copy:
    dest: /etc/sudoers.d/wheel
    content: |
      %wheel ALL=(ALL) NOPASSWD: ALL
    mode: '0440'
    owner: root
    group: root
  when: ansible_facts['distribution'] in ["Archlinux"]

- name: Install - packages workstation - vicinae-bin (AUR) via paru (Arch)
  tags: upvic
  become: true
  become_user: "{{ env_user }}"
  ansible.builtin.command: paru -S --needed --skipreview --noconfirm vicinae-bin
  register: paru_output
  changed_when: "'nothing to do' not in paru_output.stdout"  # Nur als "changed" markieren, wenn etwas installiert wurde
  when: ansible_facts['distribution'] in ["Archlinux"]

- name: Install - packages workstation - vicinae - Restore original wheel sudoers file (Arch)
  tags: upvic
  become: true
  ansible.builtin.copy:
    src: /etc/sudoers.d/wheel.bak
    dest: /etc/sudoers.d/wheel
    remote_src: true
    force: true
    mode: '0440'
    owner: root
    group: root
  when: ansible_facts['distribution'] in ["Archlinux"]

- name: Install - packages workstation - vicinae - Remove backup wheel sudoers file (Arch)
  tags: upvic
  become: true
  ansible.builtin.file:
    path: /etc/sudoers.d/wheel.bak
    state: absent
  when: ansible_facts['distribution'] in ["Archlinux"]

- name: Install - packages workstation - vicinae - show paru output (Arch)
  tags: upvic
  ansible.builtin.debug:
    var: paru_output.stdout_lines
  when: ansible_facts['distribution'] in ["Archlinux"]

- name: Install - packages workstation - vicinae - requirements (Arch)
  tags: upvic
  ansible.builtin.package:
    state: present
    name:
      # muss hier bereits vorhanden sein: paru, npm
      - rust # for 'Fuzzy Files': goldfish install
      - file # for 'Fuzzy Files': goldfish
      - python-pipx # for inst 'brotab' module
      - sqlite # shortcut conf: via sqlite cmd
      - git # clone extension repo
  when: ansible_facts['distribution'] in ["Archlinux"]

- name: Install - packages workstation - vicinae - check if brotab via pipx already installed (Arch)
  tags: upvic
  become: true
  become_user: "{{ env_user }}"
  ansible.builtin.command: pipx list
  register: pipx_list
  changed_when: false
  failed_when: pipx_list.rc != 0
  when:
    - ansible_facts['distribution'] in ["Archlinux"]

- name: Install - packages workstation - vicinae - brotab via pipx (Arch)
  tags: upvic
  become: true
  become_user: "{{ env_user }}"
  ansible.builtin.command: pipx install brotab
  register: pipx_inst_brotab
  changed_when:
    - "'installed package brotab' in pipx_inst_brotab.stdout"
    - pipx_inst_brotab.rc == 0
  failed_when: pipx_inst_brotab.rc != 0
  when:
    - ansible_facts['distribution'] in ["Archlinux"]
    - "'brotab' not in pipx_list.stdout"

# für Extension 'Fuzzy Files' # goldfish: IPC file finder
- name: Install - packages workstation - vicinae - clone goldfish git repo (Arch)
  tags: upvic
  become: true
  become_user: "{{ env_user }}"
  ansible.builtin.git:
    repo: https://github.com/sameoldlab/goldfish
    dest: /tmp/goldfish
    clone: true
    update: true
    version: main
  when: ansible_facts['distribution'] in ["Archlinux"]

- name: Install - packages workstation - vicinae - build goldfish (Arch)
  tags: upvic
  become: true
  become_user: "{{ env_user }}"
  ansible.builtin.command: cargo build --release
  args:
    chdir: /tmp/goldfish
    creates: /tmp/goldfish/target/release/gf
  when: ansible_facts['distribution'] in ["Archlinux"]

- name: Install - packages workstation - vicinae - copy goldfish executable to usr local bin (Arch)
  tags: upvic
  become: true
  ansible.builtin.copy:
    src: /tmp/goldfish/target/release/gf
    dest: /usr/local/bin/gf
    force: true
    # owner: root
    # group: root
    mode: '0755'
    remote_src: true # Quelldatei bereits auf Zielsystem, ansible soll/kann sie von dort kopieren
  when: ansible_facts['distribution'] in ["Archlinux"]
