- name: Install packages for (local) mail (Arch)
  ansible.builtin.package:
    state: present
    name:
      - postfix # Fast, easy to administer, secure mail server   # Mail Tranfer Agent (MTA)
      - mutt # text-based mail client
  when:
    - ansible_facts['distribution'] in ["Archlinux"]

- name: Install packages for (local) mail - dovecot (archlinux)
  ansible.builtin.package:
    state: present
    name:
      - dovecot # IMAP and POP3 server
  when:
    - ansible_facts['distribution'] in ["Archlinux"]
