- name: Install packages - workstation - python (Archlinux)
  ansible.builtin.package:
    state: present
    name:
      - python
      - python-pip # The PyPA recommended tool for installing Python packages
      - python-pipx # Install and Run Python Applications in Isolated Environments
      - uv # fast Python package and project manager
  when: ansible_facts['distribution'] in ["Archlinux"]
