# #####################
# ### Docker - packages
# #####################

- name: Docker - packages (Arch)
  become: true
  ansible.builtin.package:
    state: present
    name:
      - docker
      - docker-buildx
      - docker-compose
  when: ansible_facts['distribution'] == "Archlinux"
