# ######################
# ### Python Environment
# ######################

- name: Install packages - workstation - python environment - pipx (Archlinux)
  ansible.builtin.package:
    state: present
    name:
      - python-pipx # Install and Run Python Applications in Isolated Environments
  when: ansible_facts['distribution'] in ["Archlinux"]

- name: Install packages - workstation - python environment - pipx (Debian)
  ansible.builtin.package:
    state: present
    name:
      - pipx # execute binaries from Python packages in isolated environments
  when: ansible_facts['distribution'] == "Debian"
