- name: start libvirtd
  tags: VM
  service:
    name: libvirtd
    state: started
  when: ansible_virtualization_role != "guest" # or
#        ansible_os_family != "Suse"
# noch ohne nested virtualization

- name: enable libvirtd
  tags: VM
  service:
    name: libvirtd
    #state: enabled
    enabled: yes
  when: ansible_virtualization_role != "guest" # or
#        ansible_os_family != "Suse"
# noch ohne nested virtualization

#TODO: ggf. noch nested virtualization


- name: create virtual network Lab-DFS
  tags: VM
  ansible.builtin.shell:
    cmd: virsh net-define files/VM/netdump_Lab-DFS.xml && virsh net-autostart Lab-DFS
  when: ansible_virtualization_role != "guest"

- name: create virtual network Lab-Linux
  tags: VM
  ansible.builtin.shell:
    cmd: virsh net-define files/VM/netdump_Lab-Linux.xml && virsh net-autostart Lab-Linux
  when: ansible_virtualization_role != "guest"
