- name: start libvirtd
  tags: VM
  service:
    name: libvirtd
    state: started
  when: ansible_virtualization_role != "guest"

- name: enable libvirtd
  tags: VM
  service:
    name: libvirtd
    #state: enabled
    enabled: yes
  when: ansible_virtualization_role != "guest" 


- name: destroy/undefine default virtual network
  tags: VM
  ansible.builtin.shell:
    cmd: virsh net-destroy default && virsh net-undefine default
  when: ansible_virtualization_role != "guest"

- name: create virtual networks
  tags: VM
  ansible.builtin.shell:
    #cmd: ls files/VM/netdump_*.xml | xargs -I % sh -c "virsh net-define %"   # Dateiname inkl. Pfad
    chdir: files/VM/
    cmd: ls netdump_*.xml | xargs -I % sh -c "virsh net-define %"   # nur Dateiname, da vorher in Verzeichnis gewechselt und dann erst ls
  when: ansible_virtualization_role != "guest"

- name: start all virtual networks
  tags: VM
  ansible.builtin.shell:
    chdir: files/VM/
    cmd: ls netdump_*.xml | xargs -I % sh -c "echo % | cut -d _ -f 2" | xargs -I % sh -c "echo % | cut -d . -f 1" | xargs -I % sh -c "virsh net-start %"
    #z.B.:  netdump_default.xml                        default.xml                                 default                            virsh net-autostart default
  when: ansible_virtualization_role != "guest"

- name: autostart all virtual networks
  tags: VM
  ansible.builtin.shell:
    chdir: files/VM/
    cmd: ls netdump_*.xml | xargs -I % sh -c "echo % | cut -d _ -f 2" | xargs -I % sh -c "echo % | cut -d . -f 1" | xargs -I % sh -c "virsh net-autostart %"
  when: ansible_virtualization_role != "guest"


- name: create virtual machines
  tags: VM
  ansible.builtin.shell:
    chdir: files/VM/
    #cmd: ls dump_*.xml | xargs -I % sh -c "virsh create %"   # create: creates + starts vm
    cmd: ls dump_*.xml | xargs -I % sh -c "virsh define %"    # define: just creates, does not start vm
  when: ansible_virtualization_role != "guest"
