
# ##############
# ### SSH / SSHD
- name: services - start ssh (Ubuntu)
  service:
    name: ssh
    state: started
  when: ansible_distribution in ["Ubuntu"]

- name: services - enable ssh (Ubuntu)
  service: 
    name: ssh
    enabled: yes
  when: ansible_distribution in ["Ubuntu"]


- name: services - start sshd (Archlinux, Suse)
  service:
    name: sshd
    state: started
  when: ansible_distribution in ["Archlinux"] or
        ansible_os_family == "Suse"

- name: Services - enable sshd (Archlinux, Suse)
  service:
    name: sshd
    enabled: yes
  when: ansible_distribution in ["Archlinux"] or
        ansible_os_family == "Suse"



# ################
# ### vim Settings
- name: set vim config for user "sandro" (.vimrc) (all)
#  become_user: sandro
  ansible.builtin.script: "{{ env_PWD }}/tasks/config_all-servcices-misc-vim.sh" # "ansible.builtin.script:" ab ansible version 2.10, davor nur "script:"
  args:
    creates: "/home/{{ env_user }}/.vimrc"
