- name: start libvirtd
  tags: VM
  service:
    name: libvirtd
    state: started
  when: ansible_virtualization_role != "guest"

- name: enable libvirtd
  tags: VM
  service:
    name: libvirtd
    #state: enabled
    enabled: yes
  when: ansible_virtualization_role != "guest" 


- name: destroy/undefine default virtual network
  tags: VM
  ansible.builtin.shell:
    cmd: virsh net-destroy default && virsh net-undefine default
  when: ansible_virtualization_role != "guest"

#- name: create virtual networks
#  tags: VM
#  ansible.builtin.shell:
#    cmd: ls files/VM/netdump_*.xml | xargs -I % sh -c "virsh net-define %"   # Dateiname inkl. Pfad
#  when: ansible_virtualization_role != "guest"

- name: create virtual networks
  tags: VM
  ansible.builtin.shell:
    chdir: files/VM/
    cmd: ls netdump_*.xml | xargs -I % sh -c "virsh net-define %"
  when: ansible_virtualization_role != "guest"
