- name: start libvirtd
  tags: VM
  service:
    name: libvirtd
    state: started
  when: ansible_virtualization_role != "guest"

- name: enable libvirtd
  tags: VM
  service:
    name: libvirtd
    #state: enabled
    enabled: yes
  when: ansible_virtualization_role != "guest" 


- name: destroy/undefine default virtual network
  tags: VM
  ansible.builtin.shell:
    cmd: virsh net-destroy default && virsh net-undefine default
  when: ansible_virtualization_role != "guest"

- name: create virtual networks
  tags: VM
  ansible.builtin.shell:
    cmd: ls files/VM/netdump_*.xml | xargs -I % sh -c "virsh net-define %"
  when: ansible_virtualization_role != "guest"

#- name: create virtual network Lab-DFS
#  tags: VM
#  ansible.builtin.shell:
#    cmd: virsh net-define files/VM/netdump_Lab-DFS.xml && virsh net-autostart Lab-DFS
#  when: ansible_virtualization_role != "guest"

#- name: create virtual network Lab-Linux
#  tags: VM
#  ansible.builtin.shell:
#    cmd: virsh net-define files/VM/netdump_Lab-Linux.xml && virsh net-autostart Lab-Linux
#  when: ansible_virtualization_role != "guest"
