
- name: AnsibleFacts - Get desktop environment (XDG_CURRENT_DESKTOP)
  set_fact:
    env_desktop: "{{ ansible_facts['env']['XDG_CURRENT_DESKTOP']|lower }}"
#    env_desktop: "{{ lookup('env','XDG_CURRENT_DESKTOP')|lower }}"
    env_hostname: "{{ ansible_facts['hostname'] }}"

- name: AnsibleFacts - Get display server (XDG_SESSION_TYPE)
  set_fact:
    env_displayserver: "{{ ansible_facts['env']['XDG_SESSION_TYPE']|lower }}"
  when:
    - ansible_distribution == "Ubuntu"

- name: AnsibleFacts - Get datadirs (XDG_DATA_DIRS)
  set_fact:
    env_datadirs: "{{ ansible_facts['env']['XDG_DATA_DIRS'] }}"
  when:
    - ansible_distribution == "Ubuntu"
#   In Archlinux/KDE anscheinend nicht vorhanden

- name: AnsibleFacts - Get path (PATH)
  set_fact:
    env_path: "{{ ansible_facts['env']['PATH'] }}"

- name: AnsibleFacts - Get PWD (PATH)
  set_fact:
    env_PWD: "{{ ansible_facts['env']['PWD'] }}"

- name: AnsibleFacts - Get user (USER)
  set_fact:
    env_user: "{{ ansible_facts['env']['USER'] }}"

- name: AnsibleFacts - Get lsb lsb-release
  set_fact:
    env_lsb: "{{ ansible_facts['lsb']['release'] }}"   # z.B. bei Ubuntu 20.04: "20.04"

- name: AnsibleFacts - Print variable
  debug:
#    msg: "env_desktop: {{ env_desktop }}"
#    msg: "env_hostname: {{ env_hostname }}"
#    msg: "env_path: {{ env_path }}"
#    msg: "env_path: {{ env_PWD }}"
    msg: "env_user: {{ env_user }}"
