
# TODO: reorganisieren (z.B. doppelte Auflistungen bei versch. Distro, aber gleiche SW-Pakete)

####################################
### depending on desktop environment
####################################


#########
### Gnome
#########

# - gnome-shell-extensions... # -> separater Task (packages_workstation-gnomeshellstuff.yml

- name: Install packages for workstations (Ubuntu + Gnome)
  tags: workstation,gnome,ubuntu
  package:
    state: latest
    name:
      - alacarte
      - dconf-cli
      - dconf-editor
#      - deluge # -> Treanmission in Standard-Inst bereits vorhanden
      - deja-dup
      - epiphany-browser
      - evolution
      - evolution-ews
      - evolution-indicator
      - evolution-plugin-bogofilter
      - evolution-plugin-pstimport
      - evolution-plugin-spamassassin
      - evolution-plugins
      - exfat-fuse
      - exfat-utils
      - firefox # -> in Standard-Inst bereits vorhanden
      - firefox-locale-de
      - gnome-software-plugin-flatpak
#      - gnome-weather
#      - guake
      - gufw
      - hunspell-de-de-frami
      - inkscape
#      - kdeconnect -> ? gnome-shell-extension-gsconnect ?
      - language-pack-gnome-de-base
      - language-pack-gnome-de
      - luckybackup
      - nemo
#      - nextcloud-desktop # -> flatpak
      - python3-psutil
      - rhythmbox
#      - seahorse # bereits standardmäßig installiert
      - searchmonkey
      - timeshift
  when:
    - ansible_distribution == "Ubuntu"
    - env_desktop == "ubuntu:gnome"


- name: Install packages for workstations (Archlinux + Gnome)
  tags: workstation,gnome,arch
  package:
    state: latest
    name:
      - alacarte
      - atom
      - chromium
      - dconf-editor
      - deja-dup
#      - deluge # -> transmission-gtk
      - discord
      - evince
      - evolution
      - exfat-utils
      - firefox
      - firefox-i18n-de
      # ---
      # firmware:
      - alsa-firmware
      - b43-fwcutter
      - fwupd
      - gnome-firmware
      - linux-firmware
      - manjaro-firmware
      - sof-firmware
      # ---
      - foliate
#      - flameshot
#      - geary -> evolution
      - gnome-disk-utility
      - gnome-keyring
      - manjaro-keyring
      - archlinux-keyring
      - seahorse
      - gnome-maps
      - gtkhash
      - guake
      - gufw
      - hplip
      - inkscape
      - kdeconnect
      - libreoffice-still
      - libreoffice-still-de
      - lshw
      - malcontent
      - nemo
      - nemo-share
      - nemo-terminal
      - nextcloud-client
      - pamac-flatpak-plugin
      - rhythmbox
      - signal-desktop
#      - thunderbird
#      - thunderbird-i18n-de
      - timeshift
      - timeshift-autosnap
      - torbrowser-launcher
      - transmission-gtk # -> deluge
      - totem # -> vlc
#      - vlc - -> totem
      - ufw
  when:
    - ansible_distribution == "Archlinux"
    - env_desktop == "gnome"


- name: Install packages for workstations (Suse + Gnome)
  tags: workstation,gnome,suse
  package:
    state: latest
    name:
      - alacarte
      - chromium
      - dconf-editor
      - deja-dup
      - discord
      - eog
      - eog-plugin-exif-display
      - eog-plugin-map
      - eog-plugins
      - epiphany
      - evince
      - evolution
      - evolution-data-server
      - evolution-plugin-bogofilter
      - evolution-plugin-spamassassin
      - exfat-utils
      - firewall-config
#
      # firmware:
      - alsa-firmware
#      - b43-fwcutter
      - fwupd
      - gnome-firmware
#      - kernel-firmware # nicht für Tumbleweed, dort u.a.: kernel-firmware-all, ...; sollte bereits inst. sein
#
#      - linux-firmware
#      - sof-firmware
      #
      - foliate
#      - flameshot
#      - geary # -> evolution
#      - gnome-calendar # -> evolution
#      - gnome-contacts # -> evolution
#      - gnome-music # -> Rhytmbox
      - gnome-disk-utility
      - gnome-documents
      - gnome-keyring
      - gnome-maps
      - gnome-photos
      - guake
#      - gtkhash
      - hplip
      - inkscape
      - inkscape-extensions-extra
      - inkscape-extensions-gimp
      - kdeconnect-kde
      - libreoffice
      - libreoffice-filters-optional
      - libreoffice-gnome
      - libreoffice-l10n-de
#      - libreoffice-mailmerge
      - libreofficekit
      - lshw
      - lshw-gui
      - MozillaFirefox
      - nemo
      - nemo-extension-emblems
      - nemo-extension-gtkhash
      - nemo-extension-nextcloud
      - nemo-extension-preview
      - nemo-extension-seahorse
      - nemo-extension-share
      - nemo-extension-terminal
      - nextcloud-desktop
      - nextcloud-desktop-lang
      - polari
      - remmina-plugin-rdp
      - remmina-plugin-secret
      - remmina-plugin-spice
      - remmina-plugin-vnc
      - rhythmbox
      - seahorse
      - seahorse-daemon
      - simple-scan
#      - thunderbird # -> evolution
#      - thunderbird-i18n-de
#      - timeshift
#      - timeshift-autosnap
      - torbrowser-launcher
      - transmission-common
      - transmission-gtk
      - totem # -> vlc
      - totem-plugins
#      - vlc # -> totem
      - snapper
      - yast2-snapper
      - snapper-zypp-plugin
      - grub2-snapper-plugin
  when:
    - ansible_os_family == "Suse"
    - env_desktop == "gnome"



##############
### KDE Plasma
##############

- name: Install packages for workstations (Archlinux + KDE Plasma)
  tags: workstation,kde,arch
  package:
    state: latest
    name:
      - cantata
      - exfat-utils
      - firefox
      - firefox-i18n-de
      - firewalld
      - hunspell-de
      - krita
      - ktorrent
      - man-pages-de
      - mpd
      - nextcloud-client
      - pamac-flatpak-plugin
      - pamac-snap-plugin
      - qt5-translations
      - snapd
#     instead of flatpaks from repos:
      - discord
      - foliate
      - torbrowser-launcher
      - atom
      - chromium
      - libreoffice-still
      - libreoffice-still-de
      - signal-desktop
      - skanlite
      - thunderbird
      - thunderbird-i18n-de
      - yakuake
  when:
    - env_desktop == "kde"
    - ansible_distribution == "Archlinux"

- name: Install packages for workstations (Suse + KDE Plasma)
  tags: workstation,kde,suse
  package:
    state: latest
    name:
      - cantata
      - chromium
      - discord
      - discover-backend-flatpak
      - exfat-utils
      - foliate
      - hunspell
      - krita
      - ktorrent
      - libreoffice
      - libreoffice-l10n-de
      - man-pages
      - MozillaFirefox
      - MozillaFirefox-translations-common
      - MozillaThunderbird
      - MozillaThunderbird-translations-common
      - mpd
      - nextcloud-desktop
      - skanlite
      - torbrowser-launcher
      - yakuake
  when:
    - env_desktop == "kde"
    - ansible_os_family == "Suse"
