
#######################################
### NOT depending on Desktop Environmet
#######################################

- name: Install packages for workstations (basic/all)
  tags: basic, workstation, ubuntu, arch, suse
  package:
    state: latest
    name:
      - anki
#      - ansible   # bereits installiert (bootstrap)
      - clamav
      - clamtk
      - curl
      - flatpak
      - gimp
#      - gimp-lang # gibt es nicht bei ubuntu
#      - gimp-help-de
      - gitk
#      - gparted
      - grsync
#      - git   # bereits installiert (bootstrap)
      - htop
#      - hyphen-de
      - keepassxc
#      - keepassxc-lang # gibt es nicht bei ubuntu
#      - kitty   # gpu beschleunigtes terminal
      - lsb-release
#      - nano   # --> vim
      - neofetch
      - powershell   # repo wurde hinzugefügt
      - remmina
      - rsync
#      - skanlite # eher bei KDE
#      - snapd # bei Suse herausgenommen
#      - syncthing
      - terminator # bei Suse+KDE nicht unbedingt notwendig -> Konsole
      - vim
      - vlc
      - unzip

- name: install basic packages (Ubuntu)
  tags: basic, ubuntu, workstation
  package:
    state: latest
    name:
#      - snapd # bei Suse herausgenommen # bei Ubuntu schon vorhanden
#      - fwupd # firmware update daemon # bereits standardm. installiert
      - gpg
      - openssh-client
      - ssh
      - ufw
#     Miltimedia; entspechend libs sollten bereits installiert sein (wenn mei Installer ausgewählt wurde)
#      - ffmpeg
#      - x264
#      - x265
#      #- gstreamer - kram
#      - ...
# ---
#       - youtube-dl
  when: ansible_distribution == "Ubuntu"

- name: install basic packages (Ubuntu + x11 display server)
  tags: basic, ubuntu, workstation
  package:
    state: latest
    name:
      - xclip   # Voraussetzung für snap-package "espanso"
  when:
    - ansible_distribution == "Ubuntu"
    - env_displayserver == "x11"


- name: install basic packages (Archlinux)
  tags: basic, workstation, arch
  package:
    state: latest
    name:
      - snapd # bei Suse herausgenommen
  when: ansible_distribution in ["Archlinux"]


- name: install basic packages (Archlinux, Suse)
  tags: basic, workstation, arch, suse
  package:
    state: latest
    name:
      - gnupg
      - gpgme
      - ebtables
      - ipset
      - openssh
  when: ansible_distribution in ["Archlinux"] or ansible_os_family == "Suse"
#    - ansible_distribution in ["Archlinux", "openSUSE Leap"]


- name: install basic packages (Suse)
  tags: basic, workstation, Suse
  package:
    state: latest
    name:
      - firewalld
#      - exfatprogs # als ersatz für zuvor deinstallierte exfat-utils (wg. gparted); wird aktuell nicht deinstalliert
      - fuse-exfat # empfohlene Abhängigkeit ist exfat-utils
  when: ansible_os_family == "Suse"


- name: set gnome terminal - profiles and preferences (Gnome, Ansible >=2.10)
#  become_user: sandro
#
  ansible.builtin.script: "{{ env_PWD }}/tasks/config_workstation-desktopPreferences-terminal.sh" # ab ansible version 2.10
  args:
    creates: "/home/{{ env_user }}/.ansibleTerminalProfileSet"
  when:
    - env_desktop in ["gnome", "ubuntu:gnome"]
    - "ansible_version.full is version('2.10.0', '>=')"
