
# remove unnecessary preinstalled Software

#########
### Gnome
#########

# https://fostips.com/ubuntu-21-10-two-firefox-remove-snap/
- name: Uninstall snap packages for workstation - Firefox (Ubuntu >20 + Gnome)
  tags: workstation,ubuntu,arch,snap,suse
  snap:
    state: absent
    name: 
      - firefox
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version|int > 20
    - env_desktop == "ubuntu:gnome"

- name: Uninstall packages for workstations Firefox (Ubuntu >20 + Gnome)
  tags: workstation,gnome,ubuntu
  package:
    state: absent
    name:
      - firefox
  when: 
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version|int > 20
    - env_desktop == "ubuntu:gnome"

- name: Uninstall packages for workstations (Ubuntu + Gnome)
  tags: workstation,gnome,ubuntu
  package:
    state: absent
    name:
      - aisleriot
      - cheese
      - gnome-calendar
      - gnome-mahjongg
      - gnome-todo
  when: 
    - ansible_distribution == "Ubuntu"
    - env_desktop == "ubuntu:gnome"



#- name: Uninstall packages for workstations (Archlinux + Gnome)
#  tags: workstation,gnome,arch
#  package:
#    state: absent
#    name:
#      - xxx
#  when: 
#    - ansible_distribution == "Archlinux"
#    - env_desktop == "gnome"


- name: Uninstall preinstalled distro-packages for workstations (Suse + Gnome)
  tags: workstation,gnome,suse
  package:
    state: absent
    name:
      - gnome-calendar # -> evolution
      - gnome-contacts # -> evolution
      - gnome-music  # -> rhythmbox
      - cheese
      - mutt
#      - exfat-utils # -> exfatprogs wg. gparted
  when: 
    - ansible_os_family == "Suse"
    - env_desktop == "gnome"



##############
### KDE Plasma
##############

#- name: Uninstall packages for workstations (Archlinux + KDE Plasma)
#  tags: workstation,kde,arch
#  package:
#    state: absent
#    name:
#      - xxx
#  when:
#    - env_desktop == "kde"
#    - ansible_distribution == "Archlinux"


#- name: Uninstall packages for workstations (KDE Plasma + Suse)
#  tags: workstation,kde,suse
#  package:
#    state: absent
#    name:
#      - xxx
#  when:
#    - env_desktop == "kde"
#    - ansible_os_family == "Suse"

