
##############
### KDE Plasma
##############

#- name: Uninstall packages for workstations (Archlinux + KDE Plasma)
#  tags: workstation,kde,arch
#  package:
#    state: absent
#    name:
#      - xxx
#  when:
#    - env_desktop == "kde"
#    - ansible_distribution == "Archlinux"
