
# ##############
# ### KDE Plasma
# ##############

# - name: Uninstall packages for workstations (Archlinux + KDE Plasma)
#   ansible.builtin.package:
#     state: absent
#     name:
#       - yakuake
#   when:
#     - env_desktop == "kde"
#     - ansible_distribution == "Archlinux"
