
- name: Start and enable snapd (Archlinux)
  ansible.builtin.service:
    name: snapd.socket
    state: started
    enabled: true
  when: ansible_distribution == "Archlinux"

- name: Start and enable snapd apparmor (Archlinux)
  ansible.builtin.service:
    name: snapd.apparmor
    state: started
    enabled: true
  when: ansible_distribution == "Archlinux"

- name: Enable classic snap support (Archlinux)
  become: true
  become_user: root
  ansible.builtin.shell:
    cmd: if [ ! -e '/snap' ]; then ln -s /var/lib/snapd/snap /snap; fi
  when:
    - ansible_distribution == "Archlinux"

- name: Enable snap for pamac (Archlinux)
  become: true
  become_user: root
  ansible.builtin.shell:
    cmd: sed -Ei '/EnableSnap/s/^#//' /etc/pamac.conf
  when:
    - ansible_distribution == "Archlinux"

# # https://stackoverflow.com/questions/56560173/ansible-how-to-add-modify-path-variable-in-centos
# - name: 'Add {{ snapd_path }} if PATH does not exist'
#    lineinfile:
#      path: /etc/environment
#      line: 'PATH="{{ snapd_path }}"'
#      insertafter: EOF
#    when: lookup('file', '/etc/environment') is not search('^\s*PATH\s*=')

# - name: 'Add {{ snapd_path }} to PATH'
#    lineinfile:
#      path: /etc/environment
#      regexp: 'PATH=(["])((?!.*?{{ snapd_path }}).*?)(["])$'
#      line: 'PATH=\1\2:{{ snapd_path }}\3'
#      backrefs: yes
#    when: lookup('file', '/etc/environment') is search('^\s*PATH\s*=')
