
- name: Add the flathub flatpak repository remote, system (Ubuntu)
  tags: workstation,ubuntu, flatpak
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system
  when:
    - ansible_distribution == "Ubuntu"



- name: Enable flatpak for pamac (Archlinux)
  tags: workstation,arch,flatpak
  become: true
  become_user: root
  ansible.builtin.shell:
    cmd: sed -Ei '/EnableFlatpak/s/^#//' /etc/pamac.conf
  when:
    - ansible_distribution == "Archlinux"
    - pamac_conf.stat.exists   # aus: config_workstation-addrepos.yml
    # - env_lsb_id == "ManjaroLinux"

- name: Enable flatpak updates for pamac (Archlinux)
  tags: workstation,arch,flatpak
  become: true
  become_user: root
  ansible.builtin.shell:
    cmd: sed -Ei '/CheckFlatpakUpdates/s/^#//' /etc/pamac.conf
  when:
    - ansible_distribution == "Archlinux"
    - pamac_conf.stat.exists   # aus: config_workstation-addrepos.yml
    # - env_lsb_id == "ManjaroLinux"
