
- name: Add the flathub flatpak repository remote, system (All Distros)
  tags: workstation,ubuntu,suse,arch,flatpak
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system
