- name: Add the flathub flatpak repository remote, system (Ubuntu)
  tags: workstation,ubuntu, flatpak
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: system   # oder method: user
  when:
    - ansible_distribution == "Ubuntu"