
- name: Add the flathub flatpak repository remote, system (Ubuntu)
  tags: workstation,ubuntu, flatpak
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: system   # oder method: user
  when:
    - ansible_distribution == "Ubuntu"


- name: Enable flatpak for pamac (Archlinux)
  tags: workstation,arch,flatpak
  become: true
  become_user: root
  ansible.builtin.shell:
    cmd: sed -Ei '/EnableFlatpak/s/^#//' /etc/pamac.conf
  when:
    - ansible_distribution == "Archlinux"
    - pamac_conf.stat.exists   # aus: config_workstation-addrepos.yml
    # - env_lsb_id == "ManjaroLinux"

- name: Enable flatpak updates for pamac (Archlinux)
  tags: workstation,arch,flatpak
  become: true
  become_user: root
  ansible.builtin.shell:
    cmd: sed -Ei '/CheckFlatpakUpdates/s/^#//' /etc/pamac.conf
  when:
    - ansible_distribution == "Archlinux"
    - pamac_conf.stat.exists   # aus: config_workstation-addrepos.yml
    # - env_lsb_id == "ManjaroLinux"


# ### Suse: package "flatpak-remote-flathub"   # Add Flathub repository to system flatpak
