- name: Install flatpak packages for workstations (all)
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: system
  with_items:
    - "net.ankiweb.Anki"
    - "com.belmoussaoui.Authenticator"
    - "io.github.kolunmi.Bazaar" # Flatpak App Store
    - "com.brave.Browser" # ArchPacStuff
    - "com.github.finefindus.eyedropper" # Pick and format colors from screen
    - "org.kde.kasts"
    - "de.leopoldluley.Clapgrep" # One app to search through all your files (incl. PDF, Office, ...)
    - "org.cryptomator.Cryptomator"
    - "com.ranfdev.DistroShelf" # graphical interface for managing Distrobox containers on Linux
    - "com.jgraph.drawio.desktop" # diagramming tool
    - "me.iepure.devtoolbox"
    - "one.ablaze.floorp"
    - "com.microsoft.Edge"
    - "io.github.getnf.embellish"  # managing Nerd Fonts
    - "org.ferdium.Ferdium" # Messenger for the desktop - based on Franz
    - "com.github.tchx84.Flatseal"
    - "nl.hjdskes.gcolor3" # Color Picker
    - "it.mijorus.gearlever" # Manage AppImages
    - "io.github.flattool.Ignition" # add, remove, and modify startup entries
    - "io.gitlab.adhami3310.Impression" # create bootable disk drives
    - "de.willuhn.Jameica"
    - "net.cozic.joplin_desktop"
    - "de.mediathekview.MediathekView"
    - "io.missioncenter.MissionCenter"
    - "com.github.PintaProject.Pinta" # image editing, drawing and painting application with a simple yet powerful interface
    - "io.podman_desktop.PodmanDesktop"
    - "io.github.vikdevelop.SaveDesktop"
    - "de.haeckerfelix.Shortwave"
    # - "net.mkiol.SpeechNote"
    - "io.github.mfat.sshpilot"
    - "com.valvesoftware.Steam"
    - "org.tenacityaudio.Tenacity" # Audacity fork / replacement
    - "com.visualstudio.code"
    - "com.borgbase.Vorta"
    - "io.github.flattool.Warehouse" # control complex Flatpak options

- name: Install flatpak packages (Extension Manager) for Gnome (Gnome, all)
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: system
  with_items:
    - "org.gnome.Extensions"
    - "com.mattjakeman.ExtensionManager"
  when:
    - env_desktop in ["gnome"]
