# ############
# ### Desktop
# ############

# Anmerkung: dconf write gibt standardmäßig immer Exit-Code 0 zurück, selbst wenn sich nichts geändert hat.
# genau genommen müsste man immer zuerst den vorigen Wert abfragen und dann mit dem neuen Wert vergleichen

# ### Wallpapter / Background

- name: Gnome Desktop - Preferences - Create a directory for desktop-wallpaper in local user-folder (Gnome)
  ansible.builtin.file:
    path: "/home/{{ env_user }}/.local/share/backgrounds"
    state: directory
    mode: "0777"
  when:
    - env_desktop in ["gnome"]

- name: Gnome Desktop - Preferences - Copy desktop-wallpaper file to local user-folder (Gnome)
  # become: true
  # become_user: "{{ env_user }}"
  ansible.builtin.copy:
    src: "files/gnome/background/brad-huchteman-stone-mountain.jpg"
    dest: "/home/{{ env_user }}/.local/share/backgrounds/brad-huchteman-stone-mountain.jpg"
    remote_src: true
    owner: "{{ env_user }}"
    group: "{{ env_user }}"
    mode: u=rw,g=rw,o=rw
  when:
    - env_desktop in ["gnome"]

- name: Gnome Desktop - Preferences - background (Gnome)
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: '"file:///home/{{ env_user }}/.local/share/backgrounds/brad-huchteman-stone-mountain.jpg"'
    state: present # standard-wert
  when:
    - env_desktop in ["gnome"]

- name: Gnome Desktop - Preferences - dark background (Gnome)
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: '"file:///home/{{ env_user }}/.local/share/backgrounds/brad-huchteman-stone-mountain.jpg"'
    state: present
  when:
    - env_desktop in ["gnome"]

- name: Gnome Desktop - Preferences - Set desktop-wallpaper picture-options (Gnome)
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"
    state: present
  when:
    - env_desktop in ["gnome"]

- name: Gnome Desktop - Preferences - Set show-desktop-icons (Gnome)
  community.general.dconf:
    key: "/org/gnome/desktop/background/show-desktop-icons"
    value: "false"
    state: present
  when:
    - env_desktop in ["gnome"]

# ### Multitasking

- name: Gnome Desktop - Preferences - Multitasking - Hot Corner (off) (Gnome)
  community.general.dconf:
    key: "/org/gnome/desktop/interface/enable-hot-corners"
    value: "false"
    state: present
  when:
    - env_desktop in ["gnome"]

# ### Uhr

- name: Set desktop interface - clock-format (Gnome)
  community.general.dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'24h'"
    state: present
  when:
    - env_desktop in ["gnome"]

- name: Gnome Desktop - Preferences - Set desktop interface - clock-show-date (Gnome)
  community.general.dconf:
    key: "/org/gnome/desktop/interface/clock-show-date"
    value: "true"
    state: present
  when:
    - env_desktop in ["gnome"]

- name: Gnome Desktop - Preferences - Set desktop interface - clock-show-weekday (Gnome)
  community.general.dconf:
    key: "/org/gnome/desktop/interface/clock-show-weekday"
    value: "true"
    state: present
  when:
    - env_desktop in ["gnome"]

# ### Appearance

- name: Gnome Desktop - Preferences - Set desktop interface - color-sheme - dark (Gnome)
  community.general.dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"
    state: present
  when:
    - env_desktop in ["gnome"]

# ### gtk-theme ###

# - name: Gnome Desktop - Preferences - create a directory for gtk-theme user files in userdir (all + Gnome)
#   ansible.builtin.file:
#     path: "/home/{{ env_user }}/.themes"
#     state: directory
#     mode: '0755'
#   hen:
#     - env_desktop in ["gnome"]

- name: Gnome Desktop - Preferences - Set desktop interface - gtk-theme (Gnome)
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Orchis-Dark'"
    state: present
  when:
    - env_desktop in ["gnome"]

# ### icon-theme + Shell (user) theme ###

- name: Gnome Desktop - Preferences - Set desktop interface - icon-theme (Gnome)
  community.general.dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Papirus-Dark'"
    state: present
  when:
    - env_desktop in ["gnome"]

- name: Gnome Desktop - Preferences - Set desktop interface - Shell - user-theme (Gnome)
  community.general.dconf:
    key: "/org/gnome/shell/extensions/user-theme/name"
    value: "'Orchis-Dark'"
    state: present
  when:
    - env_desktop in ["gnome"]

# ### Battery

### Desktop interface, calendar, sceensaver, ...:
- name: Gnome Desktop - Preferences - Set desktop interface - show-battery-percentage (Gnome)
  community.general.dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "false"
    state: present
  when:
    - env_desktop in ["gnome"]

- name: Gnome Desktop - Preferences - Set desktop interface - locate-pointer (Gnome)
  community.general.dconf:
    key: "/org/gnome/desktop/interface/locate-pointer"
    value: "true"
    state: present
  when:
    - env_desktop in ["gnome"]

# ### Input sources

- name: Set desktop input-sources - show-all-sources (Gnome)
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/show-all-sources"
    value: "true"
    state: present
  when:
    - env_desktop in ["gnome"]

# ### System Region & Language

# The locale to use for dates / numbers formats
- name: Gnome Desktop - Preferences - System - Region and Language - Formats (Gnome)
  community.general.dconf:
    key: "/system/locale/region"
    value: "'de_DE.UTF-8'"
    state: present
  when:
    - env_desktop in ["gnome"]

# ### Button layout

- name: Set desktop wm preferences - button-layout (Gnome)
  community.general.dconf:
    key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "'appmenu:minimize,maximize,close'"
    state: present
  when:
    - env_desktop in ["gnome"]

# ### power settings

# interartive = Power off
- name: Gnome Desktop - Preferences - Set settings-daemon - plugin - power - power-button-action (Gnome)
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/power/power-button-action"
    value: "'nothing'"
    state: present
  when:
    - env_desktop in ["gnome"]

- name: Gnome Desktop - Preferences - Set settings-daemon - plugin - power - sleep-inactive-ac-type (Gnome)
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
    value: "'nothing'"
    state: present
  when:
    - env_desktop in ["gnome"]

- name: Gnome Desktop - Preferences - Set settings-daemon - plugin - power - sleep-inactive-battery-type (Gnome)
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type"
    value: "'nothing'"
    state: present
  when:
    - env_desktop in ["gnome"]

# ### set Display - Night Light

- name: Gnome Desktop - Preferences - Set settings-daemon - plugin - color - night-light-enabled (Gnome)
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
    value: "false"
    state: present
  when:
    - env_desktop in ["gnome"]

# ### gnome shell extensions -  preferences:

# - name: Gnome Desktop - Preferences - Set gnome shell extensions - disabled-extensions (Gnome)
#   become: true
#   become_user: "{{ env_user }}"
#   ansible.builtin.command: dconf reset /org/gnome/shell/disabled-extensions
#   # ansible.builtin.command: dconf reset -f /org/gnome/shell/disabled-extensions
#   when:
#     - env_desktop in ["gnome"]
#   register: command_dconf_changed
#   changed_when: command_dconf_changed.rc == 0

# - name: Gnome Desktop - Preferences - Set gnome shell extensions - enabled-extensions (Gnome)
#   become: true
#   become_user: "{{ env_user }}"
#   ansible.builtin.command: >
#     dconf write /org/gnome/shell/enabled-extensions
#     "['dash-to-panel@jderose9.github.com', 'user-theme@gnome-shell-extensions.gcampax.github.com']"
#   when:
#     - env_desktop in ["gnome"]
#   register: command_dconf_changed
#   changed_when: command_dconf_changed.rc == 0

# ###################################################
# TODO: ggf. GNOME Shell Apps Dashboard - Categories
# ###################################################
#
# https://specifications.freedesktop.org/menu-spec/menu-spec-latest.html
# A. Registered Categories
#
# https://github.com/BenJetson/gnome-dash-fix
# https://www.gauthampdas.com/blog/tech/linux/enabling-categories-in-gnome-3-8-shell-application-menu#
#
# dconf editor: /org/gnome/desktop/app-folders/folder-children

# - name: Gnome Desktop - Preferences - GNOME Shell Apps Dashboard - Categories (Suse + Gnome)
#  ansible.builtin.command: >
#    gsettings set org.gnome.desktop.app-folders folder-children
#    "['AudioVideo', 'Development', 'Education', 'Game', 'Graphics', 'Network', 'Office', 'Science', 'Settings', 'System', 'Utility']"
#  when:
#    - ansible_os_family == "Suse"
#    - env_desktop == "gnome"
