# #######################################
# ### Gnome Autostart Apps - Current User
# - config for all Users see:
# -https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/desktop_migration_and_administration_guide/user-sessions#autostart-applications
# #######################################

# ### Autostart-Verzeichnis erstellen (aktueller User)

- name: Gnome Desktop - Preferences - Create autostart directory for current user if it does not exist (all, Gnome)
  ansible.builtin.file:
    path: /home/{{ env_user }}/.config/autostart
    state: directory
    owner: "{{ env_user }}"
    group: "{{ env_user }}"
    mode: u=rwx # mode: '0700'
  when:
    - env_desktop in ["gnome"]

# ### Autostart-Programme
- name: Gnome Desktop - Preferences - Copy autostart file for 'Nextcloud Client' (flatpak) to local user-folder (Debian + Gnome)
  ansible.builtin.copy:
    src: "files/gnome/Gnome_AutostartApp_User_NextcloudClient_flatpak.desktop"
    dest: "/home/{{ env_user }}/.config/autostart/NextcloudClient.desktop"
    remote_src: true
    owner: "{{ env_user }}"
    group: "{{ env_user }}"
    mode: u=rw,g=rw,o=r # mode: '0664'
  when:
    - env_desktop == "gnome"
    - ansible_facts['distribution'] == "Debian"

- name: Gnome Desktop - Preferences - Copy autostart file for 'Nextcloud Client' to local user-folder (Arch + Gnome)
  ansible.builtin.copy:
    src: "files/gnome/Gnome_AutostartApp_User_NextcloudClient.desktop"
    dest: "/home/{{ env_user }}/.config/autostart/NextcloudClient.desktop"
    remote_src: true
    owner: "{{ env_user }}"
    group: "{{ env_user }}"
    mode: u=rw,g=rw,o=r # mode: '0664'
  when:
    - env_desktop == "gnome"
    - ansible_facts['distribution'] == "Archlinux"

- name: Gnome Desktop - Preferences - Copy autostart file for 'Syncthing Start' to local user-folder (Arch + Gnome)
  ansible.builtin.copy:
    src: "files/gnome/Gnome_DesktopLauncher_User_syncthing-start.desktop"
    dest: "/home/{{ env_user }}/.config/autostart/syncthing-start.desktop"
    remote_src: true
    owner: "{{ env_user }}"
    group: "{{ env_user }}"
    mode: u=rw,g=rw,o=r # mode: '0664'
  when:
    - env_desktop == "gnome"
    - ansible_facts['distribution'] == "Archlinux"
