# #################
# ### favorite apps
# #################

# nicht installierte Apps werden einfach nicht angezeigt (nach Installation schon), d.h. dass hier drin ist kein Problem
# gedit ('org.gnome.gedit.desktop') replaced with Gnome TextEditor

- name: Gnome Desktop - Preferences - Adding favorite apps to dock (Gnome, all)
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "{{ favorite_apps | to_json }}"
    state: present
  vars:
    favorite_apps:
      - com.belmoussaoui.Authenticator.desktop
      - org.keepassxc.KeePassXC.desktop
      - one.ablaze.floorp.desktop
      - org.mozilla.firefox.desktop
      # - firefox.desktop
      - com.brave.Browser.desktop
      - org.gnome.Epiphany.desktop
      - org.chromium.Chromium.desktop
      - com.microsoft.Edge.desktop
      - org.mozilla.Thunderbird.desktop
      - com.mitchellh.ghostty.desktop
      - org.gnome.Ptyxis.desktop
      - nemo.desktop
      - org.gnome.TextEditor.desktop
      - net.cozic.joplin_desktop.desktop
      - com.visualstudio.code.desktop
      # - code.desktop
      - net.ankiweb.Anki.desktop
      - org.signal.Signal.desktop
      - de.haeckerfelix.Shortwave.desktop
      - org.gnome.Rhythmbox3.desktop
      - virt-manager.desktop
  when:
    - env_desktop in ["gnome"]

# - name: Gnome Desktop - Preferences - Adding favorite apps to dock (Gnome, all)
#   community.general.dconf:
#     key: "/org/gnome/shell/favorite-apps"
#     value: |
#       ['com.belmoussaoui.Authenticator.desktop',
#       'org.keepassxc.KeePassXC.desktop',
#       'one.ablaze.floorp.desktop',
#       'org.mozilla.firefox.desktop',
#       'firefox.desktop',
#       'com.brave.Browser.desktop',
#       'org.gnome.Epiphany.desktop',
#       'org.chromium.Chromium.desktop',
#       'com.microsoft.Edge.desktop',
#       'org.mozilla.Thunderbird.desktop',
#       'com.mitchellh.ghostty.desktop',
#       'org.gnome.Ptyxis.desktop',
#       'nemo.desktop',
#       'org.gnome.TextEditor.desktop',
#       'net.cozic.joplin_desktop.desktop',
#       'com.visualstudio.code.desktop',
#       'code.desktop',
#       'net.ankiweb.Anki.desktop',
#       'org.signal.Signal.desktop',
#       'de.haeckerfelix.Shortwave.desktop',
#       'virt-manager.desktop']
#     state: present
#   when: env_desktop in ["gnome"]
