
### Ubuntu
- name: copy and decypt extensions-sync.json to users home-config (Ubuntu + Gnome)
  copy:
    src: files/gnome/extensions/ubuntu_extensions-sync.json
    dest: "/home/{{ env_user }}/.config/extensions-sync.json"
    owner: "{{ env_user }}"
    group: "{{ env_user }}"
    mode: u=rw,g=rw,o=r
    decrypt: yes
  when:
    - env_desktop == "ubuntu:gnome"


### Archlinux, Manjaro
- name: copy and decypt extensions-sync.json to users home-config (Arch + Gnome)
  copy:
    src: files/gnome/extensions/manjaro_extensions-sync
    dest: "/home/{{ env_user }}/.config/extensions-sync.json"
    owner: "{{ env_user }}"
    group: "{{ env_user }}"
    mode: u=rw,g=rw,o=r
    decrypt: yes
  when:
    - ansible_distribution == "Archlinux"
    - env_desktop == "gnome"
