# ####################
# ## GDM configuration
# ####################

- name: Gnome Desktop - Preferences - Config-workstation-Gnome-DesktopPrefs - GDM config (all, Gnome, X11)
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: "/etc/gdm/custom.conf"
    insertafter: "#WaylandEnable=false"
    line: "WaylandEnable=false"
    backup: true
  when:
    - env_desktop == "gnome"
    - env_displayserver == "x11"
