

#########
### Gnome
#########

- name: Uninstall packages for workstations (Gnome, all)
  tags: workstation,gnome
  package:
    state: absent
    name:
      - gnome-calendar
      - nano
  when: 
    - env_desktop in ["gnome", "ubuntu:gnome"]


- name: Uninstall packages for workstations (Ubuntu + Gnome)
  tags: workstation,gnome,ubuntu
  package:
    state: absent
    name:
      - aisleriot
      - cheese
      - gnome-mahjongg
      - gnome-todo
  when: 
    - ansible_distribution == "Ubuntu"
    - env_desktop == "ubuntu:gnome"


# https://fostips.com/ubuntu-21-10-two-firefox-remove-snap/
- name: Uninstall snap packages for workstation - Firefox (Ubuntu >20 + Gnome)
  tags: workstation,ubuntu,arch,snap,suse
  snap:
    state: absent
    name: 
      - firefox
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version|int > 20
    - env_desktop == "ubuntu:gnome"

- name: Uninstall packages for workstations Firefox (Ubuntu >20 + Gnome)
  tags: workstation,gnome,ubuntu
  package:
    state: absent
    name:
      - firefox
  when: 
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version|int > 20
    - env_desktop == "ubuntu:gnome"
