# #########
# ### Gnome
# #########
- name: Uninstall packages for workstations - 1 (Gnome, Arch)
  ansible.builtin.package:
    state: absent
    name:
      - aisleriot
      - five-or-more
      - four-in-a-row
      - gnome-2048
      - gnome-calendar
      - gnome-chess
      - gnome-contacts
      - gnome-games
      - gnome-maps
      - gnome-klotski
      - gnome-todo
      - hitori
  when:
    - ansible_facts['distribution'] == "Archlinux"
    - env_desktop in ["gnome"]

- name: Uninstall packages for workstations - 2 (Gnome, Arch)
  ansible.builtin.package:
    state: absent
    name:
      - gnome-software
  when:
    - ansible_facts['distribution'] == "Archlinux"
    - env_desktop == "gnome"
