- name: Gnome - shell stuff - install gnomeshell extension stuff (Arch + Gnome)
  ansible.builtin.package:
    state: present
    name:
      - gnome-shell-extensions # sollte schon installiert sein
      - gnome-shell-extension-dash-to-panel # systemweit # für User: Installation via "Extension Manager" (flatpak app)
      - gnome-tweaks
      - kdeconnect
  when:
    - ansible_facts['distribution'] in ["Archlinux"]
    - env_desktop in ["gnome"]

# Gnome shell extensions - Nachinstallation via "Extension Manager" (flatpak app):
# - AppIndicator and KStatusNotifierItem Support
# - Copyous
# - (Clipboard Indicator) # ggf. statt Copyous
# - Tiling Shell
# - Vitals
# - (Internet Speed Meter) # Transferdaten auch über Vitals
# - Weather O'Clock
# - (Dash to Panel) # systemweit via paket (s.o.)
# - GSConnect
# - User Themes
