# #########
# ### Gnome
# #########
- name: Uninstall packages for workstations (Gnome, all)
  ansible.builtin.package:
    state: absent
    name:
      - aisleriot
      - five-or-more
      - four-in-a-row
      - gnome-2048
      - gnome-calendar
      - gnome-chess
      - gnome-contacts
      - gnome-games
      - gnome-maps
      - gnome-klotski
      - gnome-todo
      - hitori
  when:
    - env_desktop in ["gnome"]
