# Citrix IcaClient (Workspace App) on Gnome 44+
# - https://bbs.archlinux.org/viewtopic.php?id=285635 (systemwide)
#   - https://andreaskaris.github.io/blog/linux/org-gnome-shell-overrides/
# - https://unix.stackexchange.com/questions/745262/settings-schema-org-gnome-shell-overrides-is-not-installed (user specific)

- name: Fix Gnome-Settings for Citrix IcaClient - copy schema file (Arch, Gnome, systemwide)
  become: true
  ansible.builtin.copy:
    src: tasks/fix/config_workstation-Gnome-org.gnome.shell.overrides.gschema.xml
    dest: /usr/share/glib-2.0/schemas/org.gnome.shell.overrides.gschema.xml
    owner: root
    group: root
    mode: '0644'
    backup: true
  when:
    - ansible_distribution in ["Archlinux"]
    - env_desktop in ["gnome"]

- name: Fix Gnome-Settings for Citrix IcaClient - recompile schemas (Arch, Gnome)
  become: true
  ansible.builtin.shell: "sudo glib-compile-schemas ."
  args:
    chdir: /usr/share/glib-2.0/schemas/
  when:
    - ansible_distribution in ["Archlinux"]
    - env_desktop in ["gnome"]
